/**
 * PATH shims that keep `BUN_INSPECT` from leaking into a session's own
 * child processes.
 *
 * THE PROBLEM. wt launches each Claude session under
 * `BUN_INSPECT=ws+unix://…` to open its inspector socket (see
 * `transport.ts`), and bun honors that variable in EVERY descendant. So
 * a bun program an agent runs inside the session tries to bind the
 * socket its own parent already owns, and the bind fails EADDRINUSE.
 *
 * WHAT THAT COSTS IS NOT UNIFORM, AND THE WORST CASE IS SILENT. This
 * comment used to promise "noise rather than damage: a ~20-line stack,
 * and the process runs on". Measured on bun 1.3.14 / macOS, that is
 * true of some programs and false of others, with no way to tell from
 * the output which one you got:
 *
 *   `bun test`, and a script that only calls console.log
 *       no stack at all, exit 0 — bun never tries.
 *   a script that touches the `Bun` global
 *       stack, exit 1, script body never runs.
 *   `supabase functions deploy` (the CLI is a bun-compiled binary)
 *       stack, exit 1, NOTHING DEPLOYED.
 *
 * The last one is the whole reason this file changed shape. The stack
 * it prints is the same stack the harmless cases print, so it reads as
 * the cosmetic noise described above; an agent that trusts it ships
 * nothing and reports success. Treat an inherited `BUN_INSPECT` as
 * fatal to whatever inherits it. (On Linux the upstream fleet saw the
 * child WIN the socket and orphan the parent's, which is worse again.)
 *
 * THE FIX. A directory of two-line `sh` shims prepended to the pane's
 * PATH, each re-execing the real binary with the variable removed. It
 * is generated by wt on the spawn path and self-heals, so there is
 * nothing to install and nothing to keep in sync. `bin/wt` scrubs the
 * variable itself, for the same reason, and does not depend on this.
 *
 * WHICH COMMANDS ARE SHIMMED IS DISCOVERED, NOT REMEMBERED. It was a
 * hand-written list of names for exactly as long as it took to find the
 * second name missing from it (`supabase`; `claude` was the first, from
 * the other direction). A list of names can only ever cover the
 * binaries someone thought of, and the failure mode for a binary nobody
 * thought of is the silent one above. So `ensureInspectShims` reads the
 * machine instead: every executable on PATH large enough to embed a bun
 * runtime whose Mach-O header names a `__BUN` segment, which is what
 * `bun build --compile` appends. On this machine that is 4 binaries out
 * of 1866 on PATH, found in ~30ms.
 *
 * `NEVER_SHIM` IS THE DANGEROUS HALF, AND IT IS THE HARNESS BINARIES.
 * `claude` is itself bun-compiled, so discovery finds it — and shimming
 * it strips `BUN_INSPECT` from the session wt just set it for, silently
 * costing every session the transport this file exists to protect.
 * That is not a hypothetical: it is what `4eda658` fixed, found only
 * when a live send failed with "no inspector socket". `shims.test.ts`
 * cross-checks `NEVER_SHIM` against the harness registry, because a
 * future harness whose binary is bun-compiled would walk into it again
 * and nothing else would notice.
 *
 * The generated directory is a SET, and it is pruned to the discovered
 * one on every spawn. Writing without pruning made it append-only ON
 * DISK while the source treated it as a list, and PATH resolves the
 * DIRECTORY: removing `claude` from the source did not remove it from
 * disk, so the fix was inert on every machine that had already run the
 * broken version — which was all of them. Discovery makes this load
 * bearing in the ordinary case too, since uninstalling a bun CLI now
 * has to un-shim it.
 */
import {
  chmodSync,
  closeSync,
  mkdirSync,
  openSync,
  readFileSync,
  readSync,
  readdirSync,
  statSync,
  unlinkSync,
  writeFileSync,
} from "node:fs";
import { delimiter, join } from "node:path";

import { config } from "../../../config.ts";
import { shQuote } from "../../../tmux/naming.ts";

/**
 * Commands wt launches sessions AS. Shimming one of these strips the
 * variable from the process wt set it for — see the header. Kept local
 * rather than derived from the harness registry because the registry
 * imports this module transitively; `shims.test.ts` asserts the two
 * agree, so drift fails a test instead of the fleet.
 */
const NEVER_SHIM = ["claude", "codex"] as const;

/**
 * Shimmed whenever present, even if discovery misses them. Discovery is
 * Mach-O-specific and finds nothing on Linux, so this floor keeps the
 * previous behavior there rather than silently regressing to none.
 */
const ALWAYS_SHIM = ["bun"] as const;

/**
 * Package-manager launchers — a category discovery CANNOT find, for a
 * reason worth stating: they are not bun programs, so no `__BUN`
 * segment; they *exec* bun programs, and they resolve them from
 * `node_modules/.bin` which they prepend to PATH ahead of ours. So a
 * shimmed `supabase` on PATH is bypassed entirely by `pnpm exec
 * supabase`, and the shimmed binary never runs.
 *
 * That is the form a repo's own docs recommend, because it pins the CLI
 * version from package.json — so the unprotected path is the one people
 * are told to use, and it fails as a bun debugger stack out of a
 * database CLI, which reads as a broken stack rather than an env
 * collision. Shimming the launcher itself covers every binary it will
 * ever resolve, including ones nobody has installed yet.
 *
 * `bunx` needs no entry: it is bun-compiled, so discovery already
 * finds it.
 */
const LAUNCHER_SHIM = ["pnpm", "pnpx", "npx", "yarn"] as const;

/**
 * Only files at least this large are probed. A bun-compiled executable
 * embeds the whole runtime (~59MB for bun 1.3.14 itself), so this is
 * far below any real one; it exists to keep the scan from opening all
 * 1866 files on PATH, not to classify anything.
 */
const MIN_COMPILED_BYTES = 8 * 1024 * 1024;

/** Mach-O load commands live at the front, so the head is enough. */
const HEAD_BYTES = 64 * 1024;

/** The segment `bun build --compile` appends to hold the module graph. */
const BUN_SEGMENT = "__BUN";

export const __testing = {
  discoverBunExecutables,
  isBunCompiled,
  pruneShims,
  shimTargets,
  ALWAYS_SHIM,
  LAUNCHER_SHIM,
  NEVER_SHIM,
  shimBody,
};

export function shimDir(): string {
  return join(config.paths.cacheRoot, "shims");
}

function shimBody(cmd: string, realPath: string): string {
  return [
    "#!/bin/sh",
    "# Generated by wt — do not edit; regenerated whenever a session starts.",
    "# Strips BUN_INSPECT so this process does not fight its parent Claude",
    "# session for that session's inspector socket. See core/harness/claude/",
    "# inject/shims.ts.",
    // shQuote, not JSON.stringify: this is a /bin/sh script, and JSON
    // escaping leaves `$` and backticks intact — both of which the
    // shell still expands inside double quotes.
    `real=${shQuote(realPath)}`,
    `if [ -x "$real" ]; then exec env -u BUN_INSPECT "$real" "$@"; fi`,
    "",
    "# The baked path is gone. This is not paranoia: a PATH entry is used",
    "# as found (unresolved, so upgrades keep tracking), and fnm hands out",
    "# a per-shell directory — ~/.local/state/fnm_multishells/<pid>_<ts> —",
    "# which is where pnpm/npx/yarn live on a machine using it. A shim",
    "# pointing at a dead one would SHADOW a working binary, which is the",
    "# failure this whole file exists to avoid, and strictly worse than",
    "# the leak it fixes. So resolve again, minus our own directory (else",
    "# we exec ourselves forever). Pure sh: no PATH to borrow tools from.",
    "#",
    "# Both the generated dir AND $0's dir are dropped, deliberately. They",
    "# are the same directory in production, and depending on that being",
    "# true is what turned a bad test copy into an unkillable exec loop:",
    "# a shim run from anywhere else stripped a path it was not in and",
    "# re-found itself. $0 is the full path when the shell resolves a",
    "# script through PATH, so its dirname is the honest self-reference.",
    "self=${0%/*}",
    "newpath=",
    "IFS=:",
    "for p in $PATH; do",
    '  [ -z "$p" ] && continue',
    `  [ "$p" = ${shQuote(shimDir())} ] && continue`,
    '  [ "$p" = "$self" ] && continue',
    '  if [ -z "$newpath" ]; then newpath=$p; else newpath=$newpath:$p; fi',
    "done",
    "unset IFS",
    'PATH=$newpath',
    "export PATH",
    `real=$(command -v ${shQuote(cmd)}) || {`,
    `  echo "wt shim: ${cmd} not found on PATH outside ${"$"}{0%/*}" >&2`,
    "  exit 127",
    "}",
    `exec env -u BUN_INSPECT "$real" "$@"`,
    "",
  ].join("\n");
}

/**
 * Find `cmd` on PATH, ignoring our own shim directory.
 *
 * The exclusion is load-bearing, not defensive: wt is frequently run
 * from INSIDE a session (an agent typing `wt status`), where the shim
 * dir is already on PATH — resolving there would point a shim at
 * itself and produce an exec loop the next time it ran.
 *
 * The PATH entry is used as found, deliberately unresolved: `claude`
 * is normally a symlink into a versioned directory, and following it
 * would pin the shim to today's version and silently stop tracking
 * upgrades.
 */
function resolveOutsideShims(cmd: string): string | null {
  const dir = shimDir();
  const path = (process.env.PATH ?? "")
    .split(delimiter)
    .filter((entry) => entry.length > 0 && entry !== dir)
    .join(delimiter);
  const found = Bun.which(cmd, { PATH: path });
  if (!found || found.startsWith(`${dir}/`)) return null;
  return found;
}

/**
 * Does this file's Mach-O header name bun's `__BUN` segment?
 *
 * Reads the head rather than scanning the file: the payload itself is
 * tens to hundreds of MB (claude is 292MB), and the load commands that
 * name the segment sit at the front. Returns false for anything it
 * cannot read — an unreadable binary is one wt leaves alone.
 */
function isBunCompiled(path: string): boolean {
  let fd: number | null = null;
  try {
    fd = openSync(path, "r");
    const head = Buffer.allocUnsafe(HEAD_BYTES);
    const read = readSync(fd, head, 0, HEAD_BYTES, 0);
    return head.subarray(0, read).includes(BUN_SEGMENT);
  } catch {
    return false;
  } finally {
    if (fd !== null) {
      try {
        closeSync(fd);
      } catch {
        // Nothing to do; the fd goes with the process.
      }
    }
  }
}

/**
 * Every bun-compiled executable resolvable on PATH, name → path as
 * found (unresolved, for the symlink reason in `resolveOutsideShims`).
 *
 * First match wins, exactly as PATH resolution does, and a name is
 * claimed by the first directory holding an executable of that name
 * whether or not it turns out to be bun-compiled — a small `foo`
 * earlier on PATH shadows a bun-compiled `foo` later, and shimming the
 * one that never runs would be worse than shimming nothing.
 */
function discoverBunExecutables(pathValue: string = process.env.PATH ?? ""): Map<string, string> {
  const dir = shimDir();
  const found = new Map<string, string>();
  const claimed = new Set<string>();
  for (const entry of pathValue.split(delimiter)) {
    if (entry.length === 0 || entry === dir) continue;
    let names: string[];
    try {
      names = readdirSync(entry);
    } catch {
      continue;
    }
    for (const name of names) {
      if (claimed.has(name)) continue;
      const full = join(entry, name);
      let st;
      try {
        st = statSync(full);
      } catch {
        // Dangling symlink: not a command, and it shadows nothing.
        continue;
      }
      if (!st.isFile() || (st.mode & 0o111) === 0) continue;
      claimed.add(name);
      if (st.size < MIN_COMPILED_BYTES) continue;
      if (isBunCompiled(full)) found.set(name, full);
    }
  }
  return found;
}

/** The shims that should exist right now, name → real binary. */
function shimTargets(): Map<string, string> {
  const targets = discoverBunExecutables();
  for (const cmd of [...ALWAYS_SHIM, ...LAUNCHER_SHIM]) {
    if (targets.has(cmd)) continue;
    const real = resolveOutsideShims(cmd);
    if (real) targets.set(cmd, real);
  }
  for (const cmd of NEVER_SHIM) targets.delete(cmd);
  return targets;
}

/**
 * Create/refresh the shim directory. Best-effort by contract: a failure
 * here costs stderr noise inside sessions, never delivery, so it must
 * not be able to fail a session launch.
 *
 * Called from the session-CREATION path only (`prepareInspectorSocket`),
 * not from argv construction — `new-session -A` builds argv even when
 * it is about to attach to a live session and throw that argv away, and
 * this does real synchronous filesystem work.
 */
export function ensureInspectShims(): void {
  const dir = shimDir();
  try {
    mkdirSync(dir, { recursive: true, mode: 0o700 });
    // mkdirSync's mode applies only on creation; re-assert it so a
    // pre-existing directory can't leave executables writable.
    chmodSync(dir, 0o700);
    const targets = shimTargets();
    for (const [cmd, real] of targets) {
      const target = join(dir, cmd);
      const body = shimBody(cmd, real);
      let current: string | null = null;
      try {
        current = readFileSync(target, "utf8");
      } catch {
        current = null;
      }
      if (current !== body) {
        writeFileSync(target, body, { mode: 0o700 });
        chmodSync(target, 0o700);
      }
    }
    pruneShims(dir, new Set(targets.keys()));
  } catch {
    // Sessions still work, just noisily.
  }
}

/**
 * Shims on disk for a command wt launches sessions AS.
 *
 * Non-empty means the transport is broken for EVERY session on this
 * machine, present and future, and no per-session remedy touches it.
 * Both diagnostics ask before blaming a session's age, because they
 * used to assert a per-session cause they had never checked ("started
 * outside wt, or before this version"; "restart them from wt"), which
 * for a whole day pointed at the one remedy guaranteed not to work.
 *
 * Deliberately narrower than "anything not in the wanted set": with the
 * set discovered from PATH, a leftover shim for an uninstalled bun CLI
 * is inert, and reporting it as this catastrophe would be a false
 * alarm of exactly the kind that gets diagnostics ignored.
 */
export function staleShims(): string[] {
  try {
    const present = new Set(readdirSync(shimDir()));
    return NEVER_SHIM.filter((cmd) => present.has(cmd));
  } catch {
    return [];
  }
}

/**
 * Delete everything in the shim directory that `keep` does not claim.
 *
 * Generic rather than a one-off unlink: the trap returns for any future
 * removal — a name dropped from discovery because the tool was
 * uninstalled, or one that turns out to belong in `NEVER_SHIM` — and
 * only the general form is self-correcting. wt owns this directory
 * exclusively and regenerates it on every spawn, so deleting unknown
 * entries costs nothing.
 */
function pruneShims(dir: string, keep: Set<string>): void {
  let entries: string[];
  try {
    entries = readdirSync(dir);
  } catch {
    return;
  }
  for (const entry of entries) {
    if (keep.has(entry)) continue;
    try {
      unlinkSync(join(dir, entry));
    } catch {
      // A stale shim we cannot remove is worth neither a throw nor a
      // failed launch; the next spawn tries again.
    }
  }
}

/**
 * PATH for a session, with the shim directory in front.
 *
 * Always returns an explicit value — never "leave PATH alone" — and
 * that is the whole point. A tmux session's default environment comes
 * from the tmux SERVER's environment, fixed when the server was born,
 * NOT from the client issuing `new-session` (verified: a second session
 * created by a client exporting a different value still saw the first
 * client's). So when wt runs from inside an already-shimmed session and
 * concluded "my PATH has it, nothing to do", the new session inherited
 * the server's older PATH, which does not — silently un-shimming
 * exactly the nested-creation case this exists for. An explicit
 * `env PATH=…` prefix is the only thing that reliably wins.
 *
 * The dir is filtered out before being prepended so repeated nesting
 * can't grow the variable without bound.
 */
export function pathWithShims(): string {
  const dir = shimDir();
  const rest = (process.env.PATH ?? "")
    .split(delimiter)
    .filter((entry) => entry.length > 0 && entry !== dir);
  return [dir, ...rest].join(delimiter);
}
