/**
 * PATH shims that keep `BUN_INSPECT` from leaking into a session's own
 * child processes.
 *
 * THE PROBLEM. wt launches each Claude session under
 * `BUN_INSPECT=ws+unix://…` to open its inspector socket (see
 * `transport.ts`), and bun honors that variable in EVERY descendant. So
 * a bun program an agent runs inside the session — `bun test`, `bun run
 * typecheck`, `wt` itself, which is `exec bun` — tries to bind the
 * socket its own parent already owns.
 *
 * On macOS that is noise rather than damage: bun fails the bind with
 * EADDRINUSE, prints a ~20-line "Failed to start inspector" stack, and
 * runs on; the session's socket is untouched. (On Linux the upstream
 * fleet observed the child WINNING the path and orphaning the parent's
 * socket. Assume the worse behavior when porting.) But a 20-line splat
 * on stderr for every command an agent runs in the wt repo is its own
 * kind of broken — it lands in test output the agent then reads.
 *
 * THE FIX. A directory of two-line `sh` shims prepended to the pane's
 * PATH, each re-execing the real binary with the variable removed. It
 * is generated by wt on the spawn path and self-heals when a shim is
 * missing or points somewhere stale, so there is nothing to install and
 * nothing to keep in sync. `bin/wt` scrubs the variable itself, for the
 * same reason, and does not depend on this.
 *
 * ONLY `bun` is shimmed, and `claude` deliberately is NOT. The session
 * itself is launched as bare `claude`, resolved through this same PATH:
 * a `claude` shim would strip `BUN_INSPECT` from the session wt just
 * set it for, silently costing every session the transport this file
 * exists to protect. (Verified the hard way — it took a live send
 * failing with "no inspector socket" to see it.) The cost is that a
 * nested `claude -p` an agent runs still prints the EADDRINUSE splat;
 * that is rare, and loud rather than silent.
 *
 * `SHIMMED` is therefore a SET, not a floor, and the directory is
 * pruned to match it on every spawn. Removing `claude` from the list
 * did not remove it from disk, PATH resolves the directory rather than
 * the list, and so the fix was inert on every machine that had already
 * run the broken version — which was all of them.
 */
import { chmodSync, mkdirSync, readFileSync, readdirSync, unlinkSync, writeFileSync } from "node:fs";
import { delimiter, join } from "node:path";

import { config } from "../../../config.ts";
import { shQuote } from "../../../tmux/naming.ts";

/** Commands that would try to bind an inherited `BUN_INSPECT` path. */
const SHIMMED = ["bun"] as const;

/** Exported for unit tests — the pruning pass is the load-bearing part. */
export const __testing = { pruneUnknownShims, SHIMMED };

export function shimDir(): string {
  return join(config.paths.cacheRoot, "shims");
}

function shimBody(realPath: string): string {
  return [
    "#!/bin/sh",
    "# Generated by wt — do not edit; regenerated whenever a session starts.",
    "# Strips BUN_INSPECT so this process does not fight its parent Claude",
    "# session for that session's inspector socket. See core/harness/claude/",
    "# inject/shims.ts.",
    // shQuote, not JSON.stringify: this is a /bin/sh script, and JSON
    // escaping leaves `$` and backticks intact — both of which the
    // shell still expands inside double quotes.
    `exec env -u BUN_INSPECT ${shQuote(realPath)} "$@"`,
    "",
  ].join("\n");
}

/**
 * Find `cmd` on PATH, ignoring our own shim directory.
 *
 * The exclusion is load-bearing, not defensive: wt is frequently run
 * from INSIDE a session (an agent typing `wt status`), where the shim
 * dir is already on PATH — resolving there would point a shim at
 * itself and produce an exec loop the next time it ran.
 *
 * The PATH entry is used as found, deliberately unresolved: `claude`
 * is normally a symlink into a versioned directory, and following it
 * would pin the shim to today's version and silently stop tracking
 * upgrades.
 */
function resolveOutsideShims(cmd: string): string | null {
  const dir = shimDir();
  const path = (process.env.PATH ?? "")
    .split(delimiter)
    .filter((entry) => entry.length > 0 && entry !== dir)
    .join(delimiter);
  const found = Bun.which(cmd, { PATH: path });
  if (!found || found.startsWith(`${dir}/`)) return null;
  return found;
}

/**
 * Create/refresh the shim directory. Best-effort by contract: a failure
 * here costs stderr noise inside sessions, never delivery, so it must
 * not be able to fail a session launch.
 *
 * Called from the session-CREATION path only (`prepareInspectorSocket`),
 * not from argv construction — `new-session -A` builds argv even when
 * it is about to attach to a live session and throw that argv away, and
 * this does real synchronous filesystem work.
 */
export function ensureInspectShims(): void {
  const dir = shimDir();
  try {
    mkdirSync(dir, { recursive: true, mode: 0o700 });
    // mkdirSync's mode applies only on creation; re-assert it so a
    // pre-existing directory can't leave executables writable.
    chmodSync(dir, 0o700);
    for (const cmd of SHIMMED) {
      const real = resolveOutsideShims(cmd);
      if (!real) continue;
      const target = join(dir, cmd);
      const body = shimBody(real);
      let current: string | null = null;
      try {
        current = readFileSync(target, "utf8");
      } catch {
        current = null;
      }
      if (current !== body) {
        writeFileSync(target, body, { mode: 0o700 });
        chmodSync(target, 0o700);
      }
    }
    pruneUnknownShims(dir);
  } catch {
    // Sessions still work, just noisily.
  }
}

/**
 * Delete anything in the shim directory that is not in `SHIMMED`.
 *
 * Writing without pruning made this set append-only ON DISK while the
 * source treated it as a list, and PATH resolution reads the DIRECTORY,
 * not the list — so a shim dropped from `SHIMMED` kept being used
 * forever. That is not hypothetical: `claude` was shimmed, then removed
 * in 4eda658 precisely because it stripped `BUN_INSPECT` from the
 * session wt had just set it for. The source fix could not heal a
 * machine that had already run the broken version, so every session on
 * this machine kept losing its transport for another day — 374 logged
 * fallbacks — and restarting a session (the advice every diagnostic
 * gave) hit the same stale file.
 *
 * Generic rather than a one-off `unlink("claude")`: the trap returns
 * for any future removal, and only the general form is self-correcting.
 * wt owns this directory exclusively and regenerates it on every spawn,
 * so deleting unknown entries costs nothing.
 */
/**
 * Shims on disk that `SHIMMED` no longer claims.
 *
 * Non-empty means the transport is broken for EVERY session on this
 * machine, present and future, and no per-session remedy touches it.
 * The diagnostics ask because both of them used to assert a
 * per-session cause they had never checked ("started outside wt, or
 * before this version"; "restart them from wt"), which for a whole day
 * pointed at the one remedy guaranteed not to work. `pruneUnknownShims`
 * makes this self-healing on the next spawn, so a non-empty result
 * should now only ever be seen by a wt that has not spawned since
 * updating.
 */
export function staleShims(): string[] {
  const keep = new Set<string>(SHIMMED);
  try {
    return readdirSync(shimDir()).filter((entry) => !keep.has(entry));
  } catch {
    return [];
  }
}

function pruneUnknownShims(dir: string): void {
  const keep = new Set<string>(SHIMMED);
  let entries: string[];
  try {
    entries = readdirSync(dir);
  } catch {
    return;
  }
  for (const entry of entries) {
    if (keep.has(entry)) continue;
    try {
      unlinkSync(join(dir, entry));
    } catch {
      // A stale shim we cannot remove is worth neither a throw nor a
      // failed launch; the next spawn tries again.
    }
  }
}

/**
 * PATH for a session, with the shim directory in front.
 *
 * Always returns an explicit value — never "leave PATH alone" — and
 * that is the whole point. A tmux session's default environment comes
 * from the tmux SERVER's environment, fixed when the server was born,
 * NOT from the client issuing `new-session` (verified: a second session
 * created by a client exporting a different value still saw the first
 * client's). So when wt runs from inside an already-shimmed session and
 * concluded "my PATH has it, nothing to do", the new session inherited
 * the server's older PATH, which does not — silently un-shimming
 * exactly the nested-creation case this exists for. An explicit
 * `env PATH=…` prefix is the only thing that reliably wins.
 *
 * The dir is filtered out before being prepended so repeated nesting
 * can't grow the variable without bound.
 */
export function pathWithShims(): string {
  const dir = shimDir();
  const rest = (process.env.PATH ?? "")
    .split(delimiter)
    .filter((entry) => entry.length > 0 && entry !== dir);
  return [dir, ...rest].join(delimiter);
}
