/**
 * Where skills and instructions actually live on this machine.
 *
 * Detection walks the real filesystem: per present harness (claude /
 * codex / opencode) it takes the harness's native path, resolves
 * symlinks to the real location, and checks whether that location is
 * generated by a rulesync pipeline (an ancestor directory containing
 * `.rulesync/`). Rulesync-generated output is WIPED on every
 * regenerate, so the durable write target there is the rulesync
 * SOURCE (`.rulesync/skills/`, and the `root: true` rule file for
 * instructions) followed by a regenerate — via the repo's own
 * `scripts/rulesync.sh` when it has one (dotfiles setups), else the
 * stock `npx rulesync generate`.
 *
 * Symlink dedupe is the other half: several harnesses routinely
 * resolve to ONE real directory (stow/dotfiles patterns, `.agents` →
 * `.claude`), and one write must count for all of them.
 */
import { existsSync, readdirSync, readFileSync, realpathSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join, parse as parsePath } from "node:path";

export type HarnessId = "claude" | "codex" | "opencode";

export type RulesyncInfo = {
  /** Repo root containing `.rulesync/`. */
  root: string;
  /** `<root>/.rulesync/skills` — durable skill sources. */
  skillsDir: string;
  /** The `root: true` rule file instructions blocks go into; null if none found. */
  rootRuleFile: string | null;
  /** Regenerate command (argv), run with cwd=root. */
  regen: string[];
};

export type SkillsTarget =
  | { kind: "native"; harnesses: HarnessId[]; dir: string }
  | { kind: "rulesync"; harnesses: HarnessId[]; rulesync: RulesyncInfo };

export type InstructionsTarget =
  | { kind: "native"; harnesses: HarnessId[]; file: string }
  | { kind: "rulesync"; harnesses: HarnessId[]; rulesync: RulesyncInfo };

export type Targets = {
  skills: SkillsTarget[];
  instructions: InstructionsTarget[];
  /** Harnesses whose config dir exists on this machine. */
  harnesses: HarnessId[];
};

/**
 * Stable identity for one install location — decline memory is scoped
 * by it so "no" for a modified copy HERE never suppresses an install
 * to a different target added later (a newly configured harness).
 */
export function targetKey(t: SkillsTarget | InstructionsTarget): string {
  if (t.kind === "rulesync") return `rulesync:${t.rulesync.root}`;
  return `native:${"dir" in t ? t.dir : t.file}`;
}

/** Resolve symlinks when the path exists; otherwise return it as-is. */
function realpathOr(p: string): string {
  try {
    return realpathSync(p);
  } catch {
    return p;
  }
}

/**
 * Nearest ancestor of `p` (inclusive) containing a `.rulesync/` dir.
 * Bounded walk; stops at the filesystem root.
 */
export function findRulesyncRoot(p: string): string | null {
  let dir = p;
  const { root: fsRoot } = parsePath(dir);
  for (let i = 0; i < 12 && dir !== fsRoot; i++) {
    if (existsSync(join(dir, ".rulesync"))) return dir;
    dir = dirname(dir);
  }
  return null;
}

/** Find the rules file with `root: true` frontmatter (the instructions home). */
function findRootRuleFile(rsRoot: string): string | null {
  const rulesDir = join(rsRoot, ".rulesync", "rules");
  if (!existsSync(rulesDir)) return null;
  let names: string[];
  try {
    names = readdirSync(rulesDir).sort();
  } catch {
    return null;
  }
  for (const name of names) {
    if (!name.endsWith(".md")) continue;
    const p = join(rulesDir, name);
    // Per-file guard: one unreadable entry (dangling symlink, perms)
    // must not hide a valid root rule sorted after it.
    try {
      const head = readFileSync(p, "utf8").slice(0, 2000);
      const fm = head.match(/^---\n([\s\S]*?)\n---/);
      if (fm && /^root:\s*true\s*$/m.test(fm[1]!)) return p;
    } catch {
      continue;
    }
  }
  return null;
}

function rulesyncInfo(root: string): RulesyncInfo {
  const script = join(root, "scripts", "rulesync.sh");
  return {
    root,
    skillsDir: join(root, ".rulesync", "skills"),
    rootRuleFile: findRootRuleFile(root),
    // A repo-local generator script wins (it may patch/relocate beyond
    // what stock rulesync does); otherwise the stock CLI.
    regen: existsSync(script) ? ["bash", script] : ["npx", "-y", "rulesync", "generate"],
  };
}

function codexHome(home: string, env: NodeJS.ProcessEnv): string {
  return env.CODEX_HOME ?? join(home, ".codex");
}

/**
 * Detect the machine's skill + instructions targets. `home`/`env` are
 * injectable for tests; production callers use the defaults.
 */
export function detectTargets(
  home: string = homedir(),
  env: NodeJS.ProcessEnv = process.env,
): Targets {
  const present: HarnessId[] = [];
  if (existsSync(join(home, ".claude"))) present.push("claude");
  if (existsSync(codexHome(home, env)) || existsSync(join(home, ".agents"))) {
    present.push("codex");
  }
  if (existsSync(join(home, ".config", "opencode"))) present.push("opencode");

  // --- skills dirs -------------------------------------------------------
  const skillDirCandidates: Array<{ harness: HarnessId; dir: string }> = [];
  for (const h of present) {
    switch (h) {
      case "claude":
        skillDirCandidates.push({ harness: h, dir: join(home, ".claude", "skills") });
        break;
      case "opencode":
        // OpenCode reads ~/.claude/skills via its standard fallback.
        skillDirCandidates.push({ harness: h, dir: join(home, ".claude", "skills") });
        break;
      case "codex": {
        // Codex scans ~/.agents/skills when present (the shared-agents
        // convention), else $CODEX_HOME/skills.
        const agents = join(home, ".agents", "skills");
        skillDirCandidates.push({
          harness: h,
          dir: existsSync(join(home, ".agents")) ? agents : join(codexHome(home, env), "skills"),
        });
        break;
      }
    }
  }
  const skills = dedupeTargets<SkillsTarget>(
    skillDirCandidates.map(({ harness, dir }) => ({ harness, resolved: realpathOr(dir) })),
    (resolved) => {
      const rsRoot = findRulesyncRoot(resolved);
      return rsRoot
        ? {
            key: `rulesync:${rsRoot}`,
            target: { kind: "rulesync", harnesses: [], rulesync: rulesyncInfo(rsRoot) },
          }
        : { key: `native:${resolved}`, target: { kind: "native", harnesses: [], dir: resolved } };
    },
  );

  // --- instructions files ------------------------------------------------
  const insCandidates: Array<{ harness: HarnessId; file: string }> = [];
  for (const h of present) {
    switch (h) {
      case "claude":
        insCandidates.push({ harness: h, file: join(home, ".claude", "CLAUDE.md") });
        break;
      case "codex":
        insCandidates.push({ harness: h, file: join(codexHome(home, env), "AGENTS.md") });
        break;
      case "opencode":
        insCandidates.push({ harness: h, file: join(home, ".config", "opencode", "AGENTS.md") });
        break;
    }
  }
  const instructions = dedupeTargets<InstructionsTarget>(
    insCandidates.map(({ harness, file }) => ({ harness, resolved: realpathOr(file) })),
    (resolved) => {
      const rsRoot = findRulesyncRoot(resolved);
      return rsRoot
        ? {
            key: `rulesync:${rsRoot}`,
            target: { kind: "rulesync", harnesses: [], rulesync: rulesyncInfo(rsRoot) },
          }
        : { key: `native:${resolved}`, target: { kind: "native", harnesses: [], file: resolved } };
    },
  );

  return { skills, instructions, harnesses: present };
}

/**
 * Collapse per-harness candidates that resolve to the same real
 * location (or the same rulesync root) into one target carrying every
 * harness it serves.
 */
function dedupeTargets<T extends { harnesses: HarnessId[] }>(
  candidates: Array<{ harness: HarnessId; resolved: string }>,
  build: (resolved: string) => { key: string; target: T },
): T[] {
  const byKey = new Map<string, T>();
  for (const { harness, resolved } of candidates) {
    const { key, target } = build(resolved);
    const existing = byKey.get(key);
    if (existing) {
      if (!existing.harnesses.includes(harness)) existing.harnesses.push(harness);
    } else {
      target.harnesses = [harness];
      byKey.set(key, target);
    }
  }
  return [...byKey.values()];
}
