/**
 * Where skills and instructions actually live on this machine.
 *
 * Detection walks the real filesystem: per configured tool it takes
 * that tool's native path, resolves symlinks to the real location,
 * and checks whether that location is generated by a rulesync
 * pipeline (an ancestor directory containing `.rulesync/`).
 * Rulesync-generated output is WIPED on every regenerate, so the
 * durable write target there is the rulesync SOURCE
 * (`.rulesync/skills/`, and the `root: true` rule file for
 * instructions) followed by a regenerate — via the repo's own
 * `scripts/rulesync.sh` when it has one (dotfiles setups), else the
 * stock `npx rulesync generate`.
 *
 * Symlink dedupe is the other half: several tools routinely resolve
 * to ONE real directory (stow/dotfiles patterns, `.agents` →
 * `.claude`), and one write must count for all of them.
 */
import { existsSync, readdirSync, readFileSync, realpathSync } from "node:fs";
import { homedir } from "node:os";
import { basename, dirname, join, parse as parsePath } from "node:path";
import { Effect } from "effect";
import type { HarnessId } from "../harness/types.ts";

/**
 * Tools this module distributes skills and instructions TO. It is
 * deliberately NOT `core/harness/types.ts`'s `HarnessId`, which is
 * the set of agents wt can start and supervise sessions for: Pi reads
 * the shared instructions file and `.agents/skills` but has no wt
 * session integration, and a tool can perfectly well be worth
 * installing into without wt ever spawning it.
 */
export type AgentToolId = "claude" | "codex" | "opencode" | "pi";

/**
 * What "nothing detected" means, in the reader's terms. Lives next to
 * the detection that produces it so the advertised paths cannot drift
 * from the ones actually probed.
 */
export const NO_TOOLS_HINT =
  "no configured coding-agent dirs found (~/.claude, ~/.codex or ~/.agents, ~/.config/opencode, $PI_CODING_AGENT_DIR)";

export type RulesyncInfo = {
  /** Repo root containing `.rulesync/`. */
  root: string;
  /** `<root>/.rulesync/skills` — durable skill sources. */
  skillsDir: string;
  /** The `root: true` rule file instructions blocks go into; null if none found. */
  rootRuleFile: string | null;
  /** Regenerate command (argv), run with cwd=root. */
  regen: string[];
};

export type SkillsTarget =
  | { kind: "native"; harnesses: AgentToolId[]; dir: string }
  | { kind: "rulesync"; harnesses: AgentToolId[]; rulesync: RulesyncInfo };

export type InstructionsTarget =
  | { kind: "native"; harnesses: AgentToolId[]; file: string }
  | { kind: "rulesync"; harnesses: AgentToolId[]; rulesync: RulesyncInfo };

export type Targets = {
  skills: SkillsTarget[];
  instructions: InstructionsTarget[];
  /** Harnesses whose config dir exists on this machine. */
  harnesses: AgentToolId[];
};

/**
 * Stable identity for one install location — decline memory is scoped
 * by it so "no" for a modified copy HERE never suppresses an install
 * to a different target added later (a newly configured harness).
 */
export function targetKey(t: SkillsTarget | InstructionsTarget): string {
  if (t.kind === "rulesync") return `rulesync:${t.rulesync.root}`;
  return `native:${"dir" in t ? t.dir : t.file}`;
}

/**
 * Resolve symlinks for a path that may not exist yet.
 *
 * `realpathSync` fails outright on a missing leaf, and handing back
 * the literal path then hides the topology it sits in: an instructions
 * file that has not been generated yet, inside a stowed rulesync tree,
 * reads as a plain native file. wt writes it straight through the stow
 * symlink into the generated output root, the pipeline's next
 * regenerate deletes it, and the unit is pending again — forever, with
 * every individual step looking like it worked. So when the leaf is
 * missing, resolve its PARENT and rejoin the basename.
 */
function realpathOr(p: string): string {
  try {
    return realpathSync(p);
  } catch {
    /* leaf missing (or unreadable) — fall back to the parent */
  }
  const parent = dirname(p);
  if (parent === p) return p;
  try {
    return join(realpathSync(parent), basename(p));
  } catch {
    return p;
  }
}

/**
 * Is this tool actually configured here? A config dir counts only
 * when it has CONTENT.
 *
 * A dotfiles/stow package that retires a tool leaves the mount point
 * behind as an empty directory, and an empty dir taken as evidence is
 * worse than no evidence at all: wt offers an install into a path the
 * dotfiles generator wipes on its next run, so the unit is pending on
 * every launch and nothing in either tool's output says why.
 */
function configured(dir: string): boolean {
  try {
    return readdirSync(dir).length > 0;
  } catch {
    return false;
  }
}

/**
 * Pi's config dir: `$PI_CODING_AGENT_DIR` when set (it is how Pi is
 * pointed at a dotfiles-owned, deliberately unstowed directory), else
 * its own home. Null when Pi isn't configured here.
 */
function piAgentDir(home: string, env: NodeJS.ProcessEnv): string | null {
  const explicit = env.PI_CODING_AGENT_DIR;
  if (explicit) return configured(explicit) ? explicit : null;
  for (const candidate of [join(home, ".pi"), join(home, ".config", "pi")]) {
    if (configured(candidate)) return candidate;
  }
  return null;
}

/**
 * Nearest ancestor of `p` (inclusive) containing a `.rulesync/` dir.
 * Bounded walk; stops at the filesystem root.
 */
export function findRulesyncRoot(p: string): string | null {
  let dir = p;
  const { root: fsRoot } = parsePath(dir);
  for (let i = 0; i < 12 && dir !== fsRoot; i++) {
    if (existsSync(join(dir, ".rulesync"))) return dir;
    dir = dirname(dir);
  }
  return null;
}

/** Find the rules file with `root: true` frontmatter (the instructions home). */
function findRootRuleFile(rsRoot: string): string | null {
  const rulesDir = join(rsRoot, ".rulesync", "rules");
  if (!existsSync(rulesDir)) return null;
  let names: string[];
  try {
    names = readdirSync(rulesDir).sort();
  } catch {
    return null;
  }
  for (const name of names) {
    if (!name.endsWith(".md")) continue;
    const p = join(rulesDir, name);
    // Per-file guard: one unreadable entry (dangling symlink, perms)
    // must not hide a valid root rule sorted after it.
    try {
      const head = readFileSync(p, "utf8").slice(0, 2000);
      const fm = head.match(/^---\n([\s\S]*?)\n---/);
      if (fm && /^root:\s*true\s*$/m.test(fm[1]!)) return p;
    } catch {
      continue;
    }
  }
  return null;
}

function rulesyncInfo(root: string): RulesyncInfo {
  const script = join(root, "scripts", "rulesync.sh");
  return {
    root,
    skillsDir: join(root, ".rulesync", "skills"),
    rootRuleFile: findRootRuleFile(root),
    // A repo-local generator script wins (it may patch/relocate beyond
    // what stock rulesync does); otherwise the stock CLI.
    regen: existsSync(script) ? ["bash", script] : ["npx", "-y", "rulesync", "generate"],
  };
}

function codexHome(home: string, env: NodeJS.ProcessEnv): string {
  return env.CODEX_HOME ?? join(home, ".codex");
}

/** The preferred directory where wt installs skills for a harness. */
export function harnessSkillsDir(
  harness: HarnessId,
  home: string = homedir(),
  env: NodeJS.ProcessEnv = process.env,
): string {
  switch (harness) {
    case "claude":
    case "opencode":
      // OpenCode reads Claude's skill directory as its standard fallback.
      return join(home, ".claude", "skills");
    case "codex":
      // Codex prefers the shared-agents convention when it is present.
      return existsSync(join(home, ".agents"))
        ? join(home, ".agents", "skills")
        : join(codexHome(home, env), "skills");
  }
}

/** Every directory a harness scans, in installation-preference order. */
export function harnessSkillDirs(
  harness: HarnessId,
  home: string = homedir(),
  env: NodeJS.ProcessEnv = process.env,
): string[] {
  const preferred = harnessSkillsDir(harness, home, env);
  if (harness !== "codex") return [preferred];

  const codex = join(codexHome(home, env), "skills");
  return preferred === codex ? [preferred] : [preferred, codex];
}

/**
 * Does the selected harness have a readable skill entrypoint at the path it
 * resolves? This intentionally accepts personal/older copies: `agent start`
 * needs to know the command exists, while `wt skills` owns freshness policy.
 */
export function harnessCanResolveSkill(
  harness: HarnessId,
  name: string,
  home: string = homedir(),
  env: NodeJS.ProcessEnv = process.env,
): Effect.Effect<boolean> {
  return Effect.sync(() => {
    for (const dir of harnessSkillDirs(harness, home, env)) {
      try {
        if (readFileSync(join(dir, name, "SKILL.md"), "utf8").trim().length > 0) {
          return true;
        }
      } catch {
        // Continue through fallback lookup paths.
      }
    }
    return false;
  });
}

/**
 * Detect the machine's skill + instructions targets. `home`/`env` are
 * injectable for tests; production callers use the defaults.
 */
export function detectTargets(
  home: string = homedir(),
  env: NodeJS.ProcessEnv = process.env,
): Targets {
  const present: AgentToolId[] = [];
  if (configured(join(home, ".claude"))) present.push("claude");
  if (configured(codexHome(home, env)) || configured(join(home, ".agents"))) {
    present.push("codex");
  }
  if (configured(join(home, ".config", "opencode"))) present.push("opencode");
  const piDir = piAgentDir(home, env);
  if (piDir !== null) present.push("pi");

  // --- skills dirs -------------------------------------------------------
  const skillDirCandidates: Array<{ harness: AgentToolId; dir: string }> = [];
  for (const h of present) {
    if (h === "pi") {
      // Pi scans the same shared ~/.agents/skills location Codex
      // does — that is how one dotfiles `.agents -> .claude` symlink
      // serves both without duplicating the tree. Its own config dir
      // is the fallback on a machine with no `.agents`.
      skillDirCandidates.push({
        harness: h,
        dir: existsSync(join(home, ".agents"))
          ? join(home, ".agents", "skills")
          : join(piDir!, "skills"),
      });
    } else {
      skillDirCandidates.push({ harness: h, dir: harnessSkillsDir(h, home, env) });
    }
  }
  const skills = dedupeTargets<SkillsTarget>(
    skillDirCandidates.map(({ harness, dir }) => ({ harness, resolved: realpathOr(dir) })),
    (resolved) => {
      const rsRoot = findRulesyncRoot(resolved);
      return rsRoot
        ? {
            key: `rulesync:${rsRoot}`,
            target: { kind: "rulesync", harnesses: [], rulesync: rulesyncInfo(rsRoot) },
          }
        : { key: `native:${resolved}`, target: { kind: "native", harnesses: [], dir: resolved } };
    },
  );

  // --- instructions files ------------------------------------------------
  const insCandidates: Array<{ harness: AgentToolId; file: string }> = [];
  for (const h of present) {
    switch (h) {
      case "claude":
        insCandidates.push({ harness: h, file: join(home, ".claude", "CLAUDE.md") });
        break;
      case "codex":
        insCandidates.push({ harness: h, file: join(codexHome(home, env), "AGENTS.md") });
        break;
      case "opencode":
        insCandidates.push({ harness: h, file: join(home, ".config", "opencode", "AGENTS.md") });
        break;
      case "pi":
        insCandidates.push({ harness: h, file: join(piDir!, "AGENTS.md") });
        break;
    }
  }
  const instructions = dedupeTargets<InstructionsTarget>(
    insCandidates.map(({ harness, file }) => ({ harness, resolved: realpathOr(file) })),
    (resolved) => {
      const rsRoot = findRulesyncRoot(resolved);
      return rsRoot
        ? {
            key: `rulesync:${rsRoot}`,
            target: { kind: "rulesync", harnesses: [], rulesync: rulesyncInfo(rsRoot) },
          }
        : { key: `native:${resolved}`, target: { kind: "native", harnesses: [], file: resolved } };
    },
  );

  return { skills, instructions, harnesses: present };
}

/**
 * Collapse per-harness candidates that resolve to the same real
 * location (or the same rulesync root) into one target carrying every
 * harness it serves.
 */
function dedupeTargets<T extends { harnesses: AgentToolId[] }>(
  candidates: Array<{ harness: AgentToolId; resolved: string }>,
  build: (resolved: string) => { key: string; target: T },
): T[] {
  const byKey = new Map<string, T>();
  for (const { harness, resolved } of candidates) {
    const { key, target } = build(resolved);
    const existing = byKey.get(key);
    if (existing) {
      if (!existing.harnesses.includes(harness)) existing.harnesses.push(harness);
    } else {
      target.harnesses = [harness];
      byKey.set(key, target);
    }
  }
  return [...byKey.values()];
}
