/**
 * Config loader.
 *
 * Reads the user `config.toml` from (in order):
 *   1. `$WT_CONFIG` (explicit override)
 *   2. `$XDG_CONFIG_HOME/wt/config.toml`
 *   3. `~/.config/wt/config.toml`
 *
 * It then searches from the current directory upward for `.wt.toml`
 * and recursively merges that repository config over the user config.
 * Arrays replace wholesale. `WT_REPO_CONFIG` carries the selected file
 * into child processes whose working directory changes (notably tmux).
 *
 * Required fields have no default — the loader collects every missing
 * or malformed field and exits with one human-readable error before
 * the TUI ever starts. Generic defaults (branch.base, slug_max_len,
 * etc.) are filled in transparently; values derived from the user's
 * branch prefix (stage.prefix, stage.default_personal) are computed
 * when omitted.
 *
 * The whole config resolves once at import time and is exposed as a
 * frozen `config` object plus named constants in `paths.ts`. Hot
 * reload is intentionally not supported — the TUI reads a stable
 * snapshot for its lifetime.
 */
import { existsSync, readFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, isAbsolute, join } from "node:path";

import type { BackendKind } from "./backend/types.ts";
import {
  mergeConfig,
  repositoryConfigPath,
  REPOSITORY_CONFIG_ENV,
  type RawConfig,
} from "./config-layer.ts";

const HOME = homedir();

function expandHome(p: string): string {
  if (p === "~") return HOME;
  if (p.startsWith("~/")) return join(HOME, p.slice(2));
  return p;
}

export type SstConfig = {
  stateBucket: string;
  statePrefix: string;
  awsProfile: string;
  /** Files in the main clone regenerated by `sst` runs; restored before fetch. */
  autoRegenPaths: readonly string[];
};

/**
 * Optional issue-tracker integration (`[issue_tracker]`). Presence of
 * the section (even empty) surfaces the issue id parsed from the branch
 * slug in the `issue` row; `url_template` upgrades the bare id into a
 * deep link. `[issue_tracker.linear]` is a preset that derives the
 * template from a Linear workspace slug.
 */
export type IssueTrackerConfig = {
  /**
   * URL template containing an `{id}` placeholder, substituted with the
   * uppercased issue id (`ENG-1883`). Null when no template is
   * configured or derivable — the issue row then shows the bare id.
   */
  urlTemplate: string | null;
  /**
   * Required id prefix (lowercase, e.g. `"coz"`) for NEW worktree
   * branches. When set, `wt new GH-970 …` fails with guidance instead
   * of minting a GH-led branch — a GitHub issue attaches as the
   * secondary id (`--gh <n>`), never as the worktree's identity.
   * Attaching to existing branches is exempt. Null = any prefix.
   */
  prefix: string | null;
};

/**
 * Optional per-worktree dev server (`[dev_server]`). wt supervises one
 * long-lived dev-server process per worktree in a tmux session
 * (`<slug>-dev`), so it survives wt restarts, auto-restarts on crash
 * (with give-up backoff so it never thrashes), and is torn down with
 * the worktree. wt owns port allocation: each slug gets a stable port
 * from `[port_base, port_base + port_range)`, persisted in wtstate and
 * substituted for `{{port}}` in `command` (also exported as `$PORT`).
 * Strictly manual — started/stopped from the `!` picker or `wt dev`.
 */
export type DevServerConfig = {
  /**
   * Shell command run via `$SHELL -lc` inside the worktree.
   * `{{port}}` substitutes the allocated port; pin the server to it
   * (e.g. `npm run dev -- --port {{port}} --strictPort`) so the
   * recorded port and the listening port can't drift.
   */
  command: string;
  /** First port of the allocation range. */
  portBase: number;
  /** Size of the allocation range. */
  portRange: number;
  /** URL template for the row/open/yank surfaces; `{{port}}` substituted. */
  urlTemplate: string;
};

export type ReviewBotUnresolvedVia = "threads" | "checklist";

/**
 * Review-bot track configuration (`[review_bot]`). The badge/row/trigger
 * that used to be hardcoded to CodeRabbit; the CodeRabbit shape remains
 * the default when the section is absent, so existing setups are
 * unchanged. Two "unresolved" models:
 *
 *   - `"threads"` (CodeRabbit): unresolved = review threads opened by
 *     `login` that aren't resolved.
 *   - `"checklist"` (e.g. a GitHub-Actions Codex reviewer): the bot
 *     posts a summary comment (identified by `summary_marker`) carrying
 *     a `- [ ]` task list; unresolved = unticked boxes in the latest
 *     summary comment. Needed when the bot posts via
 *     `github-actions[bot]`, a login shared with every other workflow —
 *     comment shape is the only reliable discriminator.
 *
 * `check_contexts` are additionally excluded from the PR checks rollup:
 * the bot has its own badge, and an advisory reviewer must never flip
 * the CI badge red.
 */
export type ReviewBotConfig = {
  /** Display name — used in row prose and the built-in re-run action. */
  name: string;
  /** Comment/thread author login. A trailing `[bot]` is ignored when matching. */
  login: string;
  /**
   * Glob patterns (case-insensitive, `*` only) matching the bot's check
   * contexts / job names. Drives pending-vs-done detection and is
   * auto-excluded from the CI checks rollup.
   */
  checkContexts: readonly string[];
  unresolvedVia: ReviewBotUnresolvedVia;
  /** Checklist mode: body prefix identifying the bot's summary comment. */
  summaryMarker: string | null;
  /**
   * Checklist mode, optional: body prefix of the bot's "review started"
   * ack comment. An ack newer than the latest summary renders as
   * `pending` — needed for comment-triggered re-runs whose check runs
   * never attach to the PR head.
   */
  pendingMarker: string | null;
  /**
   * PR comment body that re-triggers a review (e.g. `/codex-review`).
   * When set, a built-in "Re-run <name> review" action appears in the
   * `!` picker alongside user-configured actions.
   */
  rerunCommand: string | null;
};

/** Optional SSH target whose own wt instance owns remote worktrees. */
export type RemoteConfig = {
  /** SSH host or ~/.ssh/config alias. */
  host: string;
  /** Short human label used in prompts, logs, and the WezTerm tab title. */
  label: string;
  /** Path to the wt executable on the remote host. `~/` expands remotely. */
  wtPath: string;
};

/**
 * Optional webhook-receiver augmentation (`[github.events]`). When the
 * section is present, the long-lived `wt events` daemon accepts GitHub
 * webhook deliveries on a loopback port and the TUI refreshes the github
 * query on each delivery (reading the daemon's warm snapshot) instead of
 * polling on the 60s timer. Absent ⇒ classic poll-only behavior, zero
 * change. The daemon is the only thing that needs the secret; the TUI
 * just reads the snapshot + marker, so a missing secret is a daemon-start
 * error, not a config-load error.
 */
export type GithubEventsConfig = {
  /** Port the webhook daemon listens on. */
  port: number;
  /**
   * Address the daemon binds. Default `127.0.0.1` (loopback) is correct when
   * the public URL terminates on this machine (a reverse proxy / tunnel here
   * forwards to localhost). Set to a LAN IP or `0.0.0.0` only when another
   * host must reach it directly (e.g. a separate reverse-proxy box); the HMAC
   * secret is then the sole auth boundary, so keep the listener behind a
   * trusted network.
   */
  host: string;
  /**
   * Inline HMAC secret for verifying `X-Hub-Signature-256`. Prefer
   * `secretFile` so the secret isn't stored in config.toml; inline wins when
   * both are set.
   */
  secret: string | null;
  /** Path to a file holding the HMAC secret (home-expanded). */
  secretFile: string | null;
  /**
   * staleTime backstop for the github query while events are configured.
   * The webhook marker drives freshness; this only bounds staleness if the
   * daemon dies or a delivery is dropped. Default 10 min.
   */
  backstopPollMs: number;
};

export type PullRequestTarget = "github" | "linear";

export type GithubConfig = {
  /**
   * Glob patterns matched against check context names (CheckRun.name /
   * StatusContext.context). Matching contexts are dropped from the PR
   * checks rollup, so non-CI bots like CodeRabbit don't flip the badge.
   * Case-insensitive; `*` is the only wildcard.
   */
  ignoredChecks: readonly string[];
  /**
   * GitHub login requested by the `E` ("ship it") chord, which marks
   * the PR ready, requests this reviewer, and arms auto-merge in one
   * keystroke. Null disables the reviewer-request leg of the chord.
   */
  defaultReviewer: string | null;
  /**
   * Where PR browser opens should land. `github` preserves GitHub's URL;
   * `linear` rewrites GitHub PR URLs to Linear Reviews via the `linear://` deep-link scheme.
   */
  prTarget: PullRequestTarget;
  /** Webhook-receiver augmentation; null when `[github.events]` is absent. */
  events: GithubEventsConfig | null;
};

export type DiffConfig = {
  /**
   * Shell command launched on F11 inside the selected worktree's path.
   * Runs via `$SHELL -lc` (bash fallback) so pipes (`git diff | delta --paging=always`)
   * and aliases work.
   *
   * Supports a single `{{base}}` placeholder that's substituted at
   * spawn time with the worktree's resolved diff base — `origin/<trunk>`
   * for un-stacked worktrees, the parent branch ref for stacked /
   * non-trunk-PR worktrees. The default is
   * `revdiff --vim-motion --compact {{base}}`, a stacked diff TUI with
   * vim motions whose view spans commits + staged + unstaged (untracked
   * is one keypress away via `u`). When the base wt resolved against
   * changes (PR base flip, stack reroot), the existing diff session is
   * killed so the next F11 reopens against the new ref.
   *
   * Users can swap in any other diff TUI: `gitu`, `lazygit`, `tig
   * status`, `delta`-piped commands, or a custom script. Commands
   * that don't use `{{base}}` are passed through unchanged and aren't
   * subject to base-change kills.
   */
  command: string;
};

export type AiProvider = "openai" | "gemini";

type BaseAiConfig = {
  provider: AiProvider;
  /** Model id as exposed by the provider. */
  model: string;
  /** Soft budget for the prompt; we drop diff hunks largest-first to stay under it. */
  maxInputTokens: number;
  /** Per-request timeout in ms. */
  timeoutMs: number;
};

/**
 * Wire protocol for the openai provider. `"chat"` is
 * `/v1/chat/completions` — every local OpenAI-compatible server
 * (LM Studio, Ollama, llama.cpp) and older hosted models. `"responses"`
 * is `/v1/responses` — required by hosted OpenAI models that reject
 * chat completions outright (the gpt-5.6 family returns "not
 * accessible via the /chat/completions endpoint"). Explicit config
 * rather than endpoint/model sniffing: local servers are free to serve
 * any model id, so the name proves nothing about the protocol.
 */
export type OpenAiProtocol = "chat" | "responses";

export type OpenAiAiConfig = BaseAiConfig & {
  provider: "openai";
  /** OpenAI-compatible endpoint (no trailing slash). */
  endpoint: string;
  protocol: OpenAiProtocol;
  /**
   * Environment variable holding a bearer API key; sent as
   * `Authorization: Bearer <key>` on both protocols. Null preserves the
   * original unauthenticated local-endpoint behavior (no header at all).
   */
  apiKeyEnv: string | null;
  /**
   * `reasoning.effort` for the responses protocol (chat ignores it).
   * Defaults to "none": the summary task wants fast plain completion,
   * and reasoning tokens would eat the small max_output_tokens budget
   * before any text is emitted.
   */
  reasoningEffort: "none" | "minimal" | "low" | "medium" | "high";
};

export type GeminiAiConfig = BaseAiConfig & {
  provider: "gemini";
  /** Gemini API base endpoint (no trailing slash). */
  endpoint: string;
  /** Environment variable containing the Gemini API key. */
  apiKeyEnv: string;
};

export type AiConfig = OpenAiAiConfig | GeminiAiConfig;

/**
 * Pre-built action surfaced by the `!` modal. Two flavors:
 *
 *   - `claude`: prompt action; headless launches the selected primary
 *     harness's non-interactive CLI (`claude -p`, `codex exec`, or
 *     `opencode run`) with the configured prompt; the edit modal
 *     exposes an extras textarea that gets appended.
 *   - `shell`: launches `$SHELL -lc <shell>` in the worktree path; the
 *     edit modal is skipped and Enter launches directly.
 *
 * Both `prompt` and `shell` (and the user-typed extras) support
 * `{{var}}` substitution. Vars are populated per-launch from the row
 * — see `buildActionVars` in `tui/app-helpers.ts` for the full set. Unknown
 * vars pass through unchanged so typos surface in the rendered prompt.
 *
 * `{{skill_prefix}}` is the harness skill-invocation prefix (`/` for
 * Claude Code, `$` for OpenCode / Codex), chosen per launch from the
 * row's primary harness.
 * Use it for any prompt that invokes a named skill: `{{skill_prefix}}restack`.
 *
 * When `[[actions]]` is absent the built-in defaults take effect; when
 * it's present (even with one entry), the user's list is authoritative
 * — the way to drop a default is to list everything except it.
 *
 * `affects` declares which state domains the action mutates so the
 * runner can invalidate the matching cache prefixes after the action
 * exits (`git`, `github`, or `dev` — the per-worktree dev-server
 * state). Defaults: claude actions push commits → `["git", "github"]`;
 * shell actions are opaque → `[]` (opt in explicitly when needed). An
 * explicit `affects = []` opts out entirely — useful for a claude
 * action that just analyzes without writing.
 *
 * `requires` declares preconditions evaluated synchronously against
 * the current row state. The picker grays out entries whose
 * requirements aren't met (with the reason as the dim subtitle); the
 * keybinding launcher toasts the reason and skips the run. Tag
 * vocabulary:
 *   "pr"        — row has a PR (open, draft, terminal, any).
 *   "pr.ready"  — row has a non-draft, OPEN PR.
 *   "deployed"  — `isOurStageDeployed` (.sst/stage is pinned and prefix-
 *                 valid AND outputs.json references it). Matches what
 *                 `wt rm --destroy-stage` uses.
 * Default is `[]` (no preconditions).
 *
 * Both arrays are deduped at parse time. See the architecture block
 * in `state/hooks.ts` for the rules these tags participate in.
 */
export type EffectTag = "git" | "github" | "dev";
export type RequireTag = "pr" | "pr.ready" | "deployed";

/**
 * Optional picker affordances shared by both action kinds. `key` is the
 * single-char quick-pick letter in the `!` menu (auto-derived from the
 * name when omitted; see `assignActionKeys`). `group` is a section
 * label; actions sharing a group cluster under one header in the picker.
 */
type ActionUi = {
  /** Quick-pick letter in the `!` picker. Omit to auto-derive. */
  key?: string;
  /** Section label; actions with the same group cluster together. */
  group?: string;
  /**
   * Builtin-only (never parsed from config), palette-only (manager `M`
   * and the slot palettes): launch straight from the picker list,
   * skipping the edit/extras screen — for commands whose text is the
   * whole point (the palettes' raw `/compact`). The dispatch gate in
   * modal-keys/actions.ts only honors it on those surfaces; pair it
   * with `fleet`.
   */
  direct?: boolean;
  /**
   * Builtin-only: a palette command addressed to the palette's session
   * as a whole (the fleet for the manager, the slot session for `<` /
   * `>` / `\`), not a worktree row. Launched without row context — no
   * template vars, no `[re: <slug>]` prefix (see `launchSlotCommand`).
   */
  fleet?: boolean;
};

/**
 * Where a prompt action is delivered. `headless` (default) spawns a tracked
 * non-interactive run for the selected primary harness. `session` sends
 * the prompt into the worktree's live primary (F12) harness session, starting
 * it first if it isn't running, so the prompt lands in a conversation with
 * existing context and history. Session delivery is fire-and-forget: there's
 * no completion sentinel, so `affects` does not auto-refresh on finish.
 * `manager` sends to the singleton manager session instead (the fleet
 * coordinator; see docs/manager.md), prefixed with the originating slug so
 * the manager knows which worktree the prompt is about.
 *
 * `slot` is builtin-only (the parser rejects it in user config): the slot
 * palettes' entries, delivered by `launchSlotCommand` into the palette's
 * own slot session. Never routed through `launchAction`.
 */
export type ClaudeActionTarget = "headless" | "session" | "manager" | "slot";

/**
 * Per-launch user-supplied value collected by the picker before the
 * action runs. When set, picking the action opens a second picker
 * showing recent values for this action (drawn from
 * `~/.cache/wt/action-history.json`); a trailing "new…" row opens a
 * single-line input for a fresh value. The collected value substitutes
 * `{{arg}}` in `prompt` / `shell`. `null` skips the second-step prompt
 * entirely (the existing direct-launch / claude-extras flow applies).
 *
 * The label rendered in history rows comes from a per-line regex match
 * against the run's captured output — see `labelExtract` below.
 * Actions without a regex (or whose run doesn't match) keep showing
 * the raw value.
 */
type ActionArgPrompt = {
  /** Picker / input modal header. Plain text. */
  label: string;
};

export type ActionDef =
  | ({
      kind: "claude";
      id: string;
      name: string;
      prompt: string;
      target: ClaudeActionTarget;
      affects: readonly EffectTag[];
      requires: readonly RequireTag[];
      argPrompt: ActionArgPrompt | null;
      /**
       * Optional regex (source pattern, no flags) wt scans the run's
       * captured output with — last per-line match wins, capture group
       * 1 becomes the history label (falls back to the full match when
       * the pattern has no capture group). Lets the script stay vendor-
       * neutral: it just emits whatever line is naturally useful and
       * the action def declares how to pull a label out of it. Null
       * skips label extraction; the picker shows the raw value.
       */
      labelExtract: string | null;
    } & ActionUi)
  | ({
      kind: "shell";
      id: string;
      name: string;
      shell: string;
      affects: readonly EffectTag[];
      requires: readonly RequireTag[];
      argPrompt: ActionArgPrompt | null;
      /** See the claude-variant docstring. */
      labelExtract: string | null;
    } & ActionUi);

/**
 * Trigger vocabulary for `[[automations]]`. Each is a LEVEL condition
 * evaluated against the aggregated row state (see
 * `tui/automation-rules.ts` for the exact predicate + fire-key shape):
 *
 *   "pr.checks.failed"        — open PR's checks rollup is failing.
 *   "review_bot.unresolved"   — the configured review bot has
 *                               unresolved findings (threads or
 *                               checklist items, per `[review_bot]`).
 *                               "rabbit.unresolved" is accepted as a
 *                               legacy alias in config files.
 *   "review.changes_requested"— a human review requested changes.
 *   "pr.conflict"             — merge-tree probe says the branch
 *                               conflicts with its effective base.
 *   "wt.merged"               — a NON-stacked worktree's branch landed
 *                               (merged / gone / PR merged — same set
 *                               the `c` clean sweep uses). Exception:
 *                               rules running `builtin:close-issue`
 *                               also evaluate stack members — that run
 *                               never touches the worktree, so the
 *                               clean-vs-restack race the exclusion
 *                               protects against doesn't apply.
 *   "stack.parent_merged"     — a stack (worktrees chained by their
 *                               recorded fork bases) has a merged
 *                               member with open members stacked on it.
 */
export type AutomationTrigger =
  | "pr.checks.failed"
  | "review_bot.unresolved"
  | "review.changes_requested"
  | "pr.conflict"
  | "wt.merged"
  | "stack.parent_merged"
  // Work-status assertions (`wt status`; see core/work-status.ts). Level
  // conditions like everything else; the fire key carries the assertion
  // timestamp, so re-asserting the same state re-fires.
  | "status.needs_human"
  | "status.needs_testing"
  | "status.ready";

/**
 * What to do when the target worktree isn't quiescent at delivery time
 * (live session working/asking, action running, recent edits):
 * `queue` (default) holds the intent and delivers once things settle;
 * `skip` marks the fire handled and does nothing. There is deliberately
 * no "force" so delivery does not collide with an `asking` session.
 */
export type AutomationBusyPolicy = "queue" | "skip";

/** `run` targets that dispatch built-in flows instead of an [[actions]] def. */
export const AUTOMATION_BUILTINS = [
  "builtin:restack",
  "builtin:clean",
  "builtin:notify",
  "builtin:close-issue",
] as const;
export type AutomationBuiltin = (typeof AUTOMATION_BUILTINS)[number];

/**
 * One `[[automations]]` binding: when `on` holds for a worktree (and
 * the fire key is unseen), run `run` — an `[[actions]]` id (inheriting
 * its target/affects/requires) or a `builtin:` flow. No defaults ship;
 * an absent section means nothing is automated.
 */
export type AutomationDef = {
  id: string;
  on: AutomationTrigger;
  /** An [[actions]] id, or one of AUTOMATION_BUILTINS. */
  run: string;
  busy: AutomationBusyPolicy;
  /** Minimum minutes between dispatches per (rule, worktree). Null = none. */
  cooldownMinutes: number | null;
  /**
   * Quiescence window: the intent must be at least this old AND the
   * worktree free of edits for this long before delivery. Doubles as
   * the human-cancellation grace period. Defaults per trigger: merge
   * triggers (`wt.merged`, `stack.parent_merged`) can't flap — a merge
   * doesn't un-happen — so they default short; the rest default long
   * enough to ride out CI/review churn.
   */
  settleSeconds: number;
};

export type Config = {
  paths: {
    mainClone: string;
    worktreeRoot: string;
    logDir: string;
    /** Daily structured log files written by `core/logger.ts`. Derived from `logDir`. */
    appLogDir: string;
    lockDir: string;
    /** SQLite blob holding the persisted TanStack Query cache. */
    cacheDb: string;
    /**
     * `dirname(cacheDb)` — the root for ALL cross-process wt state
     * (state.json, archive.json, session-name registries, automations
     * ledger, manager reports, tmux conf, shell logs, dev scripts).
     * `cache_db` is deliberately the single knob that relocates the
     * whole state universe: point it into a fresh directory and a
     * second wt instance (another repo, a test/dogfood setup) shares
     * nothing with the first. New cross-process files go under this,
     * never under a hardcoded `~/.cache/wt`.
     */
    cacheRoot: string;
    /** WezTerm CLI used for tab naming; null falls back to PATH lookup. */
    weztermCli: string | null;
  };
  branch: {
    prefix: string;
    base: string;
    /** Regex (no flags) matching an issue ID at the start of a slug. */
    idPattern: string;
    slugMaxLen: number;
  };
  stage: {
    prefix: string;
    /** Stage name reserved for the user's personal env; excluded from orphans. */
    defaultPersonal: string;
    /** Public domain for stage URLs; null = stage URLs are not constructed. */
    domain: string | null;
  };
  lifecycle: {
    envFilesToCopy: readonly string[];
    /** Glob patterns copied from the main clone into each new worktree. */
    copyGlobs: readonly string[];
    /**
     * Dependency-install command run in a fresh git-worktree checkout
     * (the rift backend skips installs — packages ride the CoW clone).
     * Executed via `$SHELL -lc` so pipes and PATH additions work. Null
     * (the default) auto-detects from the checkout's lockfile:
     * bun.lock(b) → bun, pnpm-lock.yaml → pnpm, yarn.lock → yarn,
     * package-lock.json / npm-shrinkwrap.json → npm; no lockfile skips
     * the install with a note.
     */
    installCommand: string | null;
  };
  /**
   * How new worktrees are materialized on disk. `git-worktree` (default)
   * uses `git worktree`; `rift` uses copy-on-write clones (needs the
   * `rift` binary + `rift init` on the main clone). Orthogonal to any
   * remote axis — this is the LOCAL materialization mechanism. Existing
   * checkouts of the other kind keep working after a flip (the backend
   * is detected from disk at removal, not stored).
   */
  backend: { kind: BackendKind };
  sst: SstConfig | null;
  issueTracker: IssueTrackerConfig | null;
  reviewBot: ReviewBotConfig;
  devServer: DevServerConfig | null;
  remote: RemoteConfig | null;
  ai: AiConfig | null;
  diff: DiffConfig;
  github: GithubConfig;
  actions: readonly ActionDef[];
  automations: readonly AutomationDef[];
  ui: {
    /** Detail-pane row order. Unknown ids are ignored, missing ones hidden. */
    rows: readonly string[];
    /**
     * List-pane badge slots to suppress (`ui.hidden_badges`). Opt-out
     * rather than an ordered allow-list like `rows`: the cluster's
     * left-to-right order is designed (`[bot] [review] [pr] [checks]`
     * reads as one "state of this PR" run), and an allow-list would also
     * hide any slot added in a later version from anyone who set it.
     */
    hiddenBadges: ReadonlySet<BadgeSlot>;
    /**
     * List-pane row ordering inside each section. `status` (default)
     * ranks rows by work-status urgency (ready first, landed
     * last; see core/work-status.ts), with the manual order as the
     * stable tie-break — a no-op until statuses exist. `manual` is the
     * pure hand order. Stack sections always keep spine order.
     */
    sort: "status" | "manual";
  };
  skills: {
    /**
     * Check bundled agent skills/instructions for pending updates when
     * the TUI starts, prompting y/n once per update (declines are
     * remembered per content version). `[skills] startup_check = false`
     * turns the startup prompt off; `wt skills` stays available.
     */
    startupCheck: boolean;
  };
  manager: {
    /**
     * Standing brief for the manager session to proactively send
     * workflow papercuts/nits it observes during fleet work to the
     * wt-source session, which reviews and applies them. Opt-in
     * (`[manager] wt_feedback = true`): the manager skill reads this
     * flag from the config TOML at session time — most users don't
     * run a session on the wt repo itself.
     */
    wtFeedback: boolean;
  };
  update: {
    /**
     * Check the wt source clone for upstream commits when the TUI
     * starts — at most once a day — and prompt y/n to fast-forward
     * (a "no" is remembered until origin moves again). Skipped
     * silently when the clone is dirty or ahead. `[update]
     * startup_check = false` turns it off; `wt update` stays
     * available. See core/update.ts.
     */
    startupCheck: boolean;
  };
};

/**
 * The glyph slots `tui/badge-cluster.tsx` composes, in cluster order.
 * Named for what they signal, not their glyph — `ui.hidden_badges`
 * entries are matched against these. The ids double as the validation
 * set, so a typo fails the load rather than silently doing nothing.
 */
export const BADGE_SLOTS = [
  "action",
  "dirty",
  "rebase",
  "deploy",
  "session",
  "review_bot",
  "review",
  "pr",
  "checks",
] as const;

export type BadgeSlot = (typeof BADGE_SLOTS)[number];

/** Generic-only defaults. Anything specific to a user/repo lives in `config.toml`. */
const GENERIC_DEFAULTS = {
  branch: {
    base: "main",
    // Matches Linear/Jira/Shortcut-style team-id prefixes (eng-1234, INF-99…).
    idPattern: "^[a-z]+-(\\d+)(?:-|$)",
    slugMaxLen: 50,
  },
  lifecycle: {
    envFilesToCopy: [".env"] as const,
    copyGlobs: [] as const,
  },
  paths: {
    cacheDb: join(HOME, ".cache", "wt", "cache.sqlite"),
    weztermCli:
      process.platform === "darwin"
        ? "/Applications/WezTerm.app/Contents/MacOS/wezterm"
        : null,
  },
  // SST v3 convention: per-stage Pulumi state file lives at
  // `<state_prefix><stage>.json`. The default file regenerated per
  // stage is `sst-env.d.ts`.
  sst: {
    autoRegenPaths: ["sst-env.d.ts"] as const,
  },
  diff: {
    // revdiff: stacked diff TUI with vim motions. `{{base}}` resolves
    // to the trunk branch so the view spans commits + staged +
    // unstaged (untracked is one keypress away via `u`). No watch
    // flag — manual refresh on `R`; the tmux session preserves scroll
    // position across F11 detaches, which matters more than always-
    // current state.
    //
    // TODO: hook revdiff annotations into the harness action loop (F12
    // enters the selected primary harness now, not just claude). Add
    // `-o {{worktree}}/.wt-review.md` to the command so a review pass
    // dumps annotations to a known path, then a new harness action
    // ("address review annotations") whose prompt reads that file and
    // addresses each comment. Cleaner than depending on revdiff's
    // separate Claude Code plugin since wt already owns the action
    // plumbing.
    command: "revdiff --vim-motion --compact {{base}}",
  },
  ai: {
    provider: "openai" as const satisfies AiProvider,
    geminiEndpoint: "https://generativelanguage.googleapis.com/v1beta",
    maxInputTokens: 8000,
    // Local LLMs running on CPU/Metal can take 30s+ on a cold cache,
    // and the first request after model load is slower still. 2 min
    // gives Gemma-class models headroom; users on faster hardware can
    // dial down via [ai].timeout_ms.
    timeoutMs: 120_000,
  },
  github: {
    prTarget: "github" as const satisfies PullRequestTarget,
  },
  // CodeRabbit preset — the shape the review-bot track hardcoded before
  // it was configurable. `[review_bot]` absent ⇒ exactly the old behavior.
  reviewBot: {
    name: "CodeRabbit",
    login: "coderabbitai",
    checkContexts: ["CodeRabbit"] as const,
    unresolvedVia: "threads" as const satisfies ReviewBotUnresolvedVia,
  },
  ui: {
    // No "conflict" entry: the rebase lifecycle renders as a dedicated
    // block below the rows, not a definition row (see
    // `panels/details/rebase-block.tsx`). Old configs listing it are
    // harmless — unknown ids drop silently at resolve time. "linear" is
    // accepted as a legacy alias for "issue" at resolve time.
    rows: ["branch", "base", "issue", "stage", "dev", "pr", "claude", "git"] as const,
  },
  actions: [
    {
      kind: "claude" as const,
      id: "rebase-main",
      name: "Rebase on base",
      prompt:
        "Please rebase this branch on origin/{{base_branch}} and intelligently resolve any conflicts that come up. Push when you're done.",
      target: "headless" as const,
      affects: ["git", "github"] as const satisfies readonly EffectTag[],
      requires: [] as const satisfies readonly RequireTag[],
      argPrompt: null,
      labelExtract: null,
    },
    {
      kind: "claude" as const,
      id: "address-review",
      name: "Address PR review",
      prompt:
        "Check the requested changes from the review on the PR for this branch and address them. Push the changes, then resolve the review threads (no reply comments). When done, request a re-review from the original reviewers.",
      target: "headless" as const,
      affects: ["git", "github"] as const satisfies readonly EffectTag[],
      requires: ["pr.ready"] as const satisfies readonly RequireTag[],
      argPrompt: null,
      labelExtract: null,
    },
  ] as const,
};

/**
 * Exported so the custom-prompt action def in `core/actions.ts` (and
 * any future built-in not declared in `GENERIC_DEFAULTS.actions`) can
 * pick up the same defaults the parser applies — keeping a single
 * source of truth for "what does a claude action affect by default".
 */
export const DEFAULT_CLAUDE_AFFECTS: readonly EffectTag[] = ["git", "github"];
export const DEFAULT_SHELL_AFFECTS: readonly EffectTag[] = [];
export const DEFAULT_REQUIRES: readonly RequireTag[] = [];
const VALID_EFFECT_TAGS = new Set<EffectTag>(["git", "github", "dev"]);
const VALID_REQUIRE_TAGS = new Set<RequireTag>(["pr", "pr.ready", "deployed"]);

function configPath(): { path: string; present: boolean } {
  const explicit = process.env.WT_CONFIG;
  if (explicit) {
    const p = expandHome(explicit);
    return { path: p, present: existsSync(p) };
  }
  const xdg = process.env.XDG_CONFIG_HOME;
  const dir = xdg ? expandHome(xdg) : join(HOME, ".config");
  const p = join(dir, "wt", "config.toml");
  return { path: p, present: existsSync(p) };
}

type Raw = RawConfig;

function obj(v: unknown): Raw | null {
  return v && typeof v === "object" && !Array.isArray(v) ? (v as Raw) : null;
}

function strArr(v: unknown, fallback: readonly string[]): readonly string[] {
  if (!Array.isArray(v)) return fallback;
  const out: string[] = [];
  for (const x of v) if (typeof x === "string") out.push(x);
  return out;
}

function unsafeCopyGlob(pattern: string): boolean {
  return isAbsolute(pattern) ||
    /^[a-zA-Z]:[\\/]/.test(pattern) ||
    pattern.split(/[\\/]+/).includes("..");
}

class Errors {
  private list: string[] = [];
  add(msg: string) {
    this.list.push(msg);
  }
  /** Read a required string field; record an error and return "" on miss. */
  reqStr(parent: Raw | null, section: string, key: string): string {
    const v = parent?.[key];
    if (typeof v === "string" && v.length > 0) return v;
    this.add(`${section}.${key} is required`);
    return "";
  }
  optStr(parent: Raw | null, key: string, fallback: string): string {
    const v = parent?.[key];
    return typeof v === "string" && v.length > 0 ? v : fallback;
  }
  optStrOrNull(parent: Raw | null, key: string): string | null {
    const v = parent?.[key];
    return typeof v === "string" && v.length > 0 ? v : null;
  }
  optNum(parent: Raw | null, key: string, fallback: number): number {
    const v = parent?.[key];
    return typeof v === "number" && Number.isFinite(v) ? v : fallback;
  }
  /** Read an optional string-enum field; record an error on a value outside `allowed`. */
  optEnum<T extends string>(
    parent: Raw | null,
    section: string,
    key: string,
    allowed: readonly T[],
    fallback: T,
  ): T {
    const v = parent?.[key];
    if (v === undefined) return fallback;
    if (typeof v === "string" && (allowed as readonly string[]).includes(v)) {
      return v as T;
    }
    this.add(`${section}.${key} must be one of: ${allowed.join(", ")}`);
    return fallback;
  }
  /** True when any recorded error message starts with `prefix`. */
  has(prefix: string): boolean {
    return this.list.some((l) => l.startsWith(prefix));
  }
  flush(configFile: string, hints: readonly string[] = []): void {
    if (this.list.length === 0) return;
    const lines = this.list.map((l) => `  - ${l}`).join("\n");
    const hintLines = hints.length > 0
      ? `\n${hints.map((h) => `hint: ${h}`).join("\n")}\n`
      : "";
    process.stderr.write(
      `wt: invalid config at ${configFile}\n${lines}\n${hintLines}` +
        `\nSee src/core/config.ts for the full schema.\n`,
    );
    process.exit(1);
  }
}

function loadRaw(path: string, present: boolean, errs: Errors): Raw {
  if (!present) {
    errs.add(`config file not found at ${path}`);
    return {};
  }
  try {
    const text = readFileSync(path, "utf8");
    const parsed = Bun.TOML.parse(text);
    return obj(parsed) ?? {};
  } catch (err) {
    errs.add(`failed to parse ${path}: ${(err as Error).message}`);
    return {};
  }
}

function build(raw: Raw, errs: Errors): Config {
  const paths = obj(raw.paths);
  const branch = obj(raw.branch);
  const stage = obj(raw.stage);
  const lifecycle = obj(raw.lifecycle);
  const deploy = obj(raw.deploy);
  const sstRaw = deploy ? obj(deploy.sst) : null;
  const tracker = obj(raw.issue_tracker);
  const linearRaw = tracker ? obj(tracker.linear) : null;
  const remoteRaw = obj(raw.remote);
  const ui = obj(raw.ui);

  const branchPrefix = errs.reqStr(branch, "branch", "prefix");
  const branchBase = errs.optStr(branch, "base", GENERIC_DEFAULTS.branch.base);
  const idPattern = errs.optStr(branch, "id_pattern", GENERIC_DEFAULTS.branch.idPattern);
  // Compile-validate at load time — stage.ts does `new RegExp(idPattern,
  // "i")` at module init with no try/catch, so a bad pattern would
  // otherwise throw an uncaught SyntaxError on startup instead of
  // failing the config loader with a normal error.
  try {
    new RegExp(idPattern);
  } catch (err) {
    errs.add(`branch.id_pattern: invalid regex (${(err as Error).message})`);
  }
  const slugMaxLen = errs.optNum(branch, "slug_max_len", GENERIC_DEFAULTS.branch.slugMaxLen);

  const mainClone = expandHome(errs.reqStr(paths, "paths", "main_clone"));
  const worktreeRoot = expandHome(errs.reqStr(paths, "paths", "worktree_root"));
  const cacheDb = expandHome(errs.optStr(paths, "cache_db", GENERIC_DEFAULTS.paths.cacheDb));
  // Everything cross-process anchors here; log_dir/lock_dir default
  // relative to it so relocating cache_db moves the whole universe.
  const cacheRoot = dirname(cacheDb);
  const logDir = expandHome(errs.optStr(paths, "log_dir", join(cacheRoot, "logs")));
  // Sibling subdir for structured app logs — keeps daily `wt-*.log`
  // files separate from the per-worktree `<slug>-*.log` destroy logs
  // that `wt logs <slug>` reads. Not user-configurable; fold into
  // `log_dir` if the user moved that.
  const appLogDir = join(logDir, "app");
  const lockDir = expandHome(errs.optStr(paths, "lock_dir", join(cacheRoot, "locks")));
  const weztermCliRaw =
    errs.optStrOrNull(paths, "wezterm_cli") ?? GENERIC_DEFAULTS.paths.weztermCli;
  const weztermCli = weztermCliRaw ? expandHome(weztermCliRaw) : null;

  // Stage prefix derives from branch.prefix when omitted — the
  // overwhelmingly common shape is `<branch.prefix>-<stage>`. Same
  // for the personal stage name, which is just the bare prefix.
  const stagePrefix = errs.optStr(stage, "prefix", `${branchPrefix}-`);
  const stageDefault = errs.optStr(stage, "default_personal", branchPrefix);
  const stageDomain = errs.optStrOrNull(stage, "domain");

  const envFiles = strArr(lifecycle?.env_files_to_copy, GENERIC_DEFAULTS.lifecycle.envFilesToCopy);
  const copyGlobs = strArr(lifecycle?.copy_globs, GENERIC_DEFAULTS.lifecycle.copyGlobs);
  if (copyGlobs.some(unsafeCopyGlob)) {
    errs.add("lifecycle.copy_globs entries must be relative paths without '..' segments");
  }
  const installCommand = errs.optStrOrNull(lifecycle, "install_command");

  // Worktree backend — opt-in. Absent section (or absent key) means the
  // default `git-worktree`; `rift` switches new creates to CoW clones.
  const backendRaw = obj(raw.backend);
  const backendKind = errs.optEnum(
    backendRaw,
    "backend",
    "kind",
    ["git-worktree", "rift"] as const satisfies readonly BackendKind[],
    "git-worktree",
  );

  // SST and Linear are entirely optional — absence of the section
  // disables the integration. When the section IS present, every
  // required field within it must be set.
  const sst: SstConfig | null = sstRaw === null
    ? null
    : {
      stateBucket: errs.reqStr(sstRaw, "deploy.sst", "state_bucket"),
      statePrefix: errs.reqStr(sstRaw, "deploy.sst", "state_prefix"),
      awsProfile: errs.reqStr(sstRaw, "deploy.sst", "aws_profile"),
      autoRegenPaths: strArr(sstRaw.auto_regen_paths, GENERIC_DEFAULTS.sst.autoRegenPaths),
    };

  // [issue_tracker] presence alone enables the issue row (bare parsed
  // id); an explicit url_template — or the [issue_tracker.linear]
  // preset, which derives one from the workspace — upgrades it to a
  // deep link. An explicit template wins over the preset.
  let issueTracker: IssueTrackerConfig | null = null;
  if (tracker !== null) {
    const explicitTemplate = errs.optStrOrNull(tracker, "url_template");
    if (explicitTemplate && !explicitTemplate.includes("{id}")) {
      errs.add("issue_tracker.url_template must contain the {id} placeholder");
    }
    let urlTemplate = explicitTemplate;
    if (!urlTemplate && linearRaw !== null) {
      const workspace = errs.reqStr(linearRaw, "issue_tracker.linear", "workspace");
      // linear:// deep-link scheme — opens the desktop app directly.
      urlTemplate = `linear://${workspace}/issue/{id}`;
    }
    const prefix = errs.optStrOrNull(tracker, "prefix");
    if (prefix && !/^[a-z]+$/.test(prefix)) {
      errs.add("issue_tracker.prefix must be lowercase letters (e.g. \"coz\")");
    }
    issueTracker = { urlTemplate, prefix: prefix || null };
  }

  // [review_bot] — absent means the CodeRabbit preset, preserving the
  // previously-hardcoded default behavior. Checklist mode has no sane
  // CodeRabbit-shaped fallbacks: the login and summary marker identify a
  // *different* bot, so both must be explicit, and the check-context
  // default flips to "none" rather than inheriting CodeRabbit's.
  const reviewBotRaw = obj(raw.review_bot);
  const reviewBotVia = errs.optEnum(
    reviewBotRaw,
    "review_bot",
    "unresolved_via",
    ["threads", "checklist"] as const satisfies readonly ReviewBotUnresolvedVia[],
    GENERIC_DEFAULTS.reviewBot.unresolvedVia,
  );
  const isChecklist = reviewBotVia === "checklist";
  const reviewBot: ReviewBotConfig = {
    name: errs.optStr(reviewBotRaw, "name", GENERIC_DEFAULTS.reviewBot.name),
    login: (isChecklist
      ? errs.reqStr(reviewBotRaw, "review_bot", "login")
      : errs.optStr(reviewBotRaw, "login", GENERIC_DEFAULTS.reviewBot.login)
    ).replace(/\[bot\]$/, ""),
    checkContexts: strArr(
      reviewBotRaw?.check_contexts,
      isChecklist ? [] : GENERIC_DEFAULTS.reviewBot.checkContexts,
    ),
    unresolvedVia: reviewBotVia,
    summaryMarker: errs.optStrOrNull(reviewBotRaw, "summary_marker"),
    pendingMarker: errs.optStrOrNull(reviewBotRaw, "pending_marker"),
    rerunCommand: errs.optStrOrNull(reviewBotRaw, "rerun_command"),
  };
  if (isChecklist && !reviewBot.summaryMarker) {
    errs.add('review_bot.summary_marker is required when unresolved_via = "checklist"');
  }

  // [dev_server] — optional; presence turns on the per-worktree dev
  // server (row, bolt, `!` picker builtins, `wt dev`).
  const devServerRaw = obj(raw.dev_server);
  let devServer: DevServerConfig | null = null;
  if (devServerRaw !== null) {
    const portBase = errs.optNum(devServerRaw, "port_base", 8100);
    const portRange = errs.optNum(devServerRaw, "port_range", 100);
    if (!Number.isInteger(portBase) || portBase < 1 || portBase > 65_535) {
      errs.add("dev_server.port_base must be a port number (1-65535)");
    }
    if (!Number.isInteger(portRange) || portRange < 1 || portBase + portRange > 65_536) {
      errs.add("dev_server.port_range must keep the range within 1-65535");
    }
    devServer = {
      command: errs.reqStr(devServerRaw, "dev_server", "command"),
      portBase,
      portRange,
      urlTemplate: errs.optStr(devServerRaw, "url", "http://localhost:{{port}}/"),
    };
  }

  const remoteHost = remoteRaw === null
    ? ""
    : errs.reqStr(remoteRaw, "remote", "host");
  const remote: RemoteConfig | null = remoteRaw === null
    ? null
    : {
      host: remoteHost,
      label: errs.optStr(remoteRaw, "label", remoteHost),
      wtPath: errs.optStr(remoteRaw, "wt_path", "~/.wt/bin/wt"),
    };

  const aiRaw = obj(raw.ai);
  const aiProvider = errs.optEnum(
    aiRaw,
    "ai",
    "provider",
    ["openai", "gemini"] as const satisfies readonly AiProvider[],
    GENERIC_DEFAULTS.ai.provider,
  );
  const aiBase = aiRaw === null
    ? null
    : {
      model: errs.reqStr(aiRaw, "ai", "model"),
      maxInputTokens: errs.optNum(
        aiRaw,
        "max_input_tokens",
        GENERIC_DEFAULTS.ai.maxInputTokens,
      ),
      timeoutMs: errs.optNum(
        aiRaw,
        "timeout_ms",
        GENERIC_DEFAULTS.ai.timeoutMs,
      ),
    };
  const ai: AiConfig | null = aiBase === null
    ? null
    : aiProvider === "gemini"
      ? {
        provider: "gemini",
        endpoint: errs.optStr(
          aiRaw,
          "endpoint",
          GENERIC_DEFAULTS.ai.geminiEndpoint,
        ).replace(/\/+$/, ""),
        apiKeyEnv: errs.reqStr(aiRaw, "ai", "api_key_env"),
        ...aiBase,
      }
      : {
        provider: "openai",
        endpoint: errs.reqStr(aiRaw, "ai", "endpoint").replace(/\/+$/, ""),
        protocol: errs.optEnum(
          aiRaw,
          "ai",
          "protocol",
          ["chat", "responses"] as const satisfies readonly OpenAiProtocol[],
          "chat",
        ),
        apiKeyEnv: errs.optStrOrNull(aiRaw, "api_key_env"),
        reasoningEffort: errs.optEnum(
          aiRaw,
          "ai",
          "reasoning_effort",
          ["none", "minimal", "low", "medium", "high"] as const,
          "none",
        ),
        ...aiBase,
      };

  const diffRaw = obj(raw.diff);
  const diff: DiffConfig = {
    command: errs.optStr(diffRaw, "command", GENERIC_DEFAULTS.diff.command),
  };

  const rows = strArr(ui?.rows, GENERIC_DEFAULTS.ui.rows);
  const hiddenBadges = new Set<BadgeSlot>();
  for (const id of strArr(ui?.hidden_badges, [])) {
    if ((BADGE_SLOTS as readonly string[]).includes(id)) {
      hiddenBadges.add(id as BadgeSlot);
    } else {
      errs.add(
        `ui.hidden_badges: unknown badge "${id}" (expected one of ${BADGE_SLOTS.join(", ")})`,
      );
    }
  }
  const uiSort = errs.optEnum(
    ui,
    "ui",
    "sort",
    ["status", "manual"] as const,
    "status",
  );

  const skillsRaw = obj(raw.skills);
  const startupCheckRaw = skillsRaw?.startup_check;
  if (startupCheckRaw !== undefined && typeof startupCheckRaw !== "boolean") {
    errs.add("skills.startup_check must be a boolean");
  }
  const skills = { startupCheck: startupCheckRaw !== false };

  const managerRaw = obj(raw.manager);
  const wtFeedbackRaw = managerRaw?.wt_feedback;
  if (wtFeedbackRaw !== undefined && typeof wtFeedbackRaw !== "boolean") {
    errs.add("manager.wt_feedback must be a boolean");
  }
  const manager = { wtFeedback: wtFeedbackRaw === true };

  const updateRaw = obj(raw.update);
  const updateStartupRaw = updateRaw?.startup_check;
  if (updateStartupRaw !== undefined && typeof updateStartupRaw !== "boolean") {
    errs.add("update.startup_check must be a boolean");
  }
  const update = { startupCheck: updateStartupRaw !== false };

  const githubRaw = obj(raw.github);
  const githubEventsRaw = githubRaw ? obj(githubRaw.events) : null;
  const githubEventsSecretFile = githubEventsRaw
    ? errs.optStrOrNull(githubEventsRaw, "secret_file")
    : null;
  let githubEvents: GithubEventsConfig | null = null;
  if (githubEventsRaw !== null) {
    const port = errs.optNum(githubEventsRaw, "port", 8765);
    if (!Number.isInteger(port) || port < 1 || port > 65_535) {
      errs.add("github.events.port must be a port number (1-65535)");
    }
    const backstopPollMs = errs.optNum(githubEventsRaw, "backstop_poll_ms", 600_000);
    if (!Number.isFinite(backstopPollMs) || backstopPollMs <= 0) {
      errs.add("github.events.backstop_poll_ms must be a positive number");
    }
    githubEvents = {
      port,
      host: errs.optStr(githubEventsRaw, "host", "127.0.0.1"),
      secret: errs.optStrOrNull(githubEventsRaw, "secret"),
      secretFile: githubEventsSecretFile ? expandHome(githubEventsSecretFile) : null,
      backstopPollMs,
    };
  }
  const github: GithubConfig = {
    ignoredChecks: strArr(githubRaw?.ignored_checks, []),
    defaultReviewer: errs.optStrOrNull(githubRaw, "default_reviewer"),
    prTarget: errs.optEnum(
      githubRaw,
      "github",
      "pr_target",
      ["github", "linear"] as const satisfies readonly PullRequestTarget[],
      GENERIC_DEFAULTS.github.prTarget,
    ),
    events: githubEvents,
  };

  // [[actions]] is fully replaced when the user provides any entries
  // (even just one) — otherwise the built-in defaults apply. That way
  // a user can drop a default they don't want simply by listing the
  // ones they keep.
  const actions = parseActions(raw.actions, errs);
  // [[automations]] has NO defaults — automation is strictly opt-in.
  // Parsed after actions so `run` references validate against the
  // final action list.
  const automations = parseAutomations(raw.automations, actions, errs);

  return {
    paths: {
      mainClone,
      worktreeRoot,
      logDir,
      appLogDir,
      lockDir,
      cacheDb,
      cacheRoot,
      weztermCli,
    },
    branch: { prefix: branchPrefix, base: branchBase, idPattern, slugMaxLen },
    stage: { prefix: stagePrefix, defaultPersonal: stageDefault, domain: stageDomain },
    lifecycle: { envFilesToCopy: envFiles, copyGlobs, installCommand },
    backend: { kind: backendKind },
    sst,
    issueTracker,
    reviewBot,
    devServer,
    remote,
    ai,
    diff,
    github,
    actions,
    automations,
    ui: { rows, hiddenBadges, sort: uiSort },
    skills,
    manager,
    update,
  };
}

const VALID_TRIGGERS = new Set<AutomationTrigger>([
  "pr.checks.failed",
  "review_bot.unresolved",
  "review.changes_requested",
  "pr.conflict",
  "wt.merged",
  "stack.parent_merged",
  "status.needs_human",
  "status.needs_testing",
  "status.ready",
]);
/** Legacy/alternate trigger spellings, normalized before validation. */
const TRIGGER_ALIASES: Record<string, AutomationTrigger> = {
  "rabbit.unresolved": "review_bot.unresolved",
  // The status vocabulary is hyphenated (`wt status needs-human`);
  // accept the same spelling here rather than punishing consistency.
  "status.needs-human": "status.needs_human",
  "status.needs-testing": "status.needs_testing",
};
const DEFAULT_SETTLE_SECONDS = 120;
// Merge-driven triggers are un-flappy, and the typical next step (review
// the next member, mark it ready) wants the restack done promptly — keep
// only a token cancellation window.
const MERGED_SETTLE_SECONDS = 10;
const MERGE_TRIGGERS: ReadonlySet<AutomationTrigger> = new Set([
  "wt.merged",
  "stack.parent_merged",
]);
// Status assertions are deliberate writes (an agent ran `wt status`),
// not flappy derived state — and their typical run is a notification,
// where a two-minute "cancellation window" is just a late ping.
const STATUS_TRIGGERS: ReadonlySet<AutomationTrigger> = new Set([
  "status.needs_human",
  "status.needs_testing",
  "status.ready",
]);
function defaultSettleSeconds(on: AutomationTrigger): number {
  if (STATUS_TRIGGERS.has(on)) return 0;
  return MERGE_TRIGGERS.has(on) ? MERGED_SETTLE_SECONDS : DEFAULT_SETTLE_SECONDS;
}

function parseAutomations(
  raw: unknown,
  actions: readonly ActionDef[],
  errs: Errors,
): readonly AutomationDef[] {
  if (raw === undefined) return [];
  if (!Array.isArray(raw)) {
    errs.add("automations must be a TOML array of [[automations]] tables");
    return [];
  }
  const actionIds = new Set(actions.map((a) => a.id));
  const builtins = new Set<string>(AUTOMATION_BUILTINS);
  const out: AutomationDef[] = [];
  const seenIds = new Set<string>();
  for (let i = 0; i < raw.length; i++) {
    const entry = obj(raw[i]);
    const tag = `automations[${i}]`;
    if (!entry) {
      errs.add(`${tag} must be a table`);
      continue;
    }
    const id = errs.reqStr(entry, tag, "id");
    if (!id) continue;
    if (seenIds.has(id)) {
      errs.add(`${tag}.id "${id}" is duplicated`);
      continue;
    }
    const onRaw = entry.on;
    const on = typeof onRaw === "string" ? TRIGGER_ALIASES[onRaw] ?? onRaw : onRaw;
    if (typeof on !== "string" || !VALID_TRIGGERS.has(on as AutomationTrigger)) {
      errs.add(`${tag}.on must be one of: ${[...VALID_TRIGGERS].join(", ")}`);
      continue;
    }
    const run = errs.reqStr(entry, tag, "run");
    if (!run) continue;
    if (!actionIds.has(run) && !builtins.has(run)) {
      errs.add(
        `${tag}.run "${run}" is neither an [[actions]] id nor one of: ${AUTOMATION_BUILTINS.join(", ")}`,
      );
      continue;
    }
    // builtin:restack is the only run that targets a STACK rather than a
    // single worktree, and stack.parent_merged is the only trigger that
    // produces one — reject the mismatched pairings loudly.
    if (run === "builtin:restack" && on !== "stack.parent_merged") {
      errs.add(`${tag}: run "builtin:restack" requires on = "stack.parent_merged"`);
      continue;
    }
    if (run === "builtin:clean" && on === "stack.parent_merged") {
      errs.add(
        `${tag}: run "builtin:clean" targets one worktree; use "builtin:restack" for stack.parent_merged (it cleans merged members first)`,
      );
      continue;
    }
    // close-issue is defined by the landing: it closes the attached
    // GitHub issue once the branch merges. Every other trigger would
    // close issues for work that hasn't landed. And one rule covers
    // every worktree — a second is always a config mistake that would
    // just race the first to the same `gh issue close`.
    if (run === "builtin:close-issue") {
      if (on !== "wt.merged") {
        errs.add(`${tag}: run "builtin:close-issue" requires on = "wt.merged"`);
        continue;
      }
      if (out.some((a) => a.run === "builtin:close-issue")) {
        errs.add(`${tag}: only one builtin:close-issue rule is allowed`);
        continue;
      }
    }
    const busy = errs.optEnum(
      entry,
      tag,
      "busy",
      ["queue", "skip"] as const satisfies readonly AutomationBusyPolicy[],
      "queue",
    );
    const cooldownRaw = entry.cooldown_minutes;
    if (
      cooldownRaw !== undefined &&
      !(typeof cooldownRaw === "number" && Number.isFinite(cooldownRaw) && cooldownRaw > 0)
    ) {
      errs.add(`${tag}.cooldown_minutes must be a positive number`);
      continue;
    }
    const settleRaw = entry.settle_seconds;
    if (
      settleRaw !== undefined &&
      !(typeof settleRaw === "number" && Number.isFinite(settleRaw) && settleRaw >= 0)
    ) {
      errs.add(`${tag}.settle_seconds must be a non-negative number`);
      continue;
    }
    seenIds.add(id);
    out.push({
      id,
      on: on as AutomationTrigger,
      run,
      busy,
      cooldownMinutes: typeof cooldownRaw === "number" ? cooldownRaw : null,
      settleSeconds:
        typeof settleRaw === "number" ? settleRaw : defaultSettleSeconds(on as AutomationTrigger),
    });
  }
  return out;
}

function parseActions(raw: unknown, errs: Errors): readonly ActionDef[] {
  if (raw === undefined) return GENERIC_DEFAULTS.actions;
  if (!Array.isArray(raw)) {
    errs.add("actions must be a TOML array of [[actions]] tables");
    return GENERIC_DEFAULTS.actions;
  }
  const out: ActionDef[] = [];
  const seenIds = new Set<string>();
  for (let i = 0; i < raw.length; i++) {
    const entry = obj(raw[i]);
    const tag = `actions[${i}]`;
    if (!entry) {
      errs.add(`${tag} must be a table`);
      continue;
    }
    const id = errs.reqStr(entry, tag, "id");
    const name = errs.reqStr(entry, tag, "name");
    if (!id || !name) continue;
    if (seenIds.has(id)) {
      errs.add(`${tag}.id "${id}" is duplicated`);
      continue;
    }
    const promptVal = entry.prompt;
    const shellVal = entry.shell;
    const hasPrompt = typeof promptVal === "string" && promptVal.length > 0;
    const hasShell = typeof shellVal === "string" && shellVal.length > 0;
    // Distinguish "wrong type / empty" from "missing entirely" so the
    // error names the real problem instead of demanding a field the
    // user already tried to set.
    if (promptVal !== undefined && !hasPrompt) {
      errs.add(`${tag}.prompt must be a non-empty string`);
      continue;
    }
    if (shellVal !== undefined && !hasShell) {
      errs.add(`${tag}.shell must be a non-empty string`);
      continue;
    }
    if (hasPrompt && hasShell) {
      errs.add(`${tag} must set exactly one of "prompt" or "shell", not both`);
      continue;
    }
    if (!hasPrompt && !hasShell) {
      errs.add(`${tag} must set one of "prompt" or "shell"`);
      continue;
    }
    const affects = parseAffects(entry.affects, tag, errs);
    if (affects === "invalid") continue;
    const requires = parseRequires(entry.requires, tag, errs);
    if (requires === "invalid") continue;
    // Optional picker affordances. `key` must be a single character;
    // `group` a non-empty label. Both default to undefined (auto-derived
    // key / ungrouped) when absent.
    // Only /^[a-z]$/ is a valid picker binding — core/actions/builtins.ts
    // reserves uppercase and punctuation for built-ins, and an
    // out-of-range key silently dies (never rendered, never dispatchable)
    // instead of erroring, so catch it here.
    const keyRaw = entry.key;
    if (keyRaw !== undefined && !(typeof keyRaw === "string" && /^[a-z]$/.test(keyRaw))) {
      errs.add(`${tag}.key must be a single lowercase letter (a-z)`);
      continue;
    }
    const groupRaw = entry.group;
    if (groupRaw !== undefined && !(typeof groupRaw === "string" && groupRaw.length > 0)) {
      errs.add(`${tag}.group must be a non-empty string`);
      continue;
    }
    const ui: { key?: string; group?: string } = {};
    if (typeof keyRaw === "string") ui.key = keyRaw;
    if (typeof groupRaw === "string") ui.group = groupRaw;
    // `target` is prompt-action-only: it selects a supervised headless
    // primary-harness run (default) vs sending to the live F12 session.
    // Reject it on shell actions so a misplaced field fails loud instead
    // of silently doing nothing.
    const targetRaw = entry.target;
    if (targetRaw !== undefined) {
      if (!hasPrompt) {
        errs.add(`${tag}.target is only valid on a claude (prompt) action`);
        continue;
      }
      if (targetRaw !== "session" && targetRaw !== "headless" && targetRaw !== "manager") {
        errs.add(`${tag}.target must be "session", "manager", or "headless"`);
        continue;
      }
    }
    const target: ClaudeActionTarget =
      targetRaw === "session" || targetRaw === "manager"
        ? targetRaw
        : "headless";
    // `arg_prompt` is a single-line string ("company id") or omitted.
    // Stored as a small object so future extensions (placeholder text,
    // validation, multi-arg) don't churn the schema.
    const argPromptRaw = errs.optStrOrNull(entry, "arg_prompt");
    const argPrompt: ActionArgPrompt | null = argPromptRaw
      ? { label: argPromptRaw }
      : null;
    // `label_extract` is a regex source string. Compile-validate at
    // load time so a bad pattern fails the loader rather than silently
    // suppressing label extraction at run-time. Per-launch we recompile
    // (cheap; runs once per terminal action).
    const labelExtractRaw = errs.optStrOrNull(entry, "label_extract");
    if (labelExtractRaw !== null) {
      try {
        new RegExp(labelExtractRaw);
      } catch (err) {
        errs.add(`${tag}.label_extract: invalid regex (${(err as Error).message})`);
        continue;
      }
    }
    seenIds.add(id);
    if (hasPrompt) {
      out.push({
        kind: "claude",
        id,
        name,
        prompt: promptVal as string,
        target,
        affects: affects ?? DEFAULT_CLAUDE_AFFECTS,
        requires: requires ?? DEFAULT_REQUIRES,
        argPrompt,
        labelExtract: labelExtractRaw,
        ...ui,
      });
    } else {
      out.push({
        kind: "shell",
        id,
        name,
        shell: shellVal as string,
        affects: affects ?? DEFAULT_SHELL_AFFECTS,
        requires: requires ?? DEFAULT_REQUIRES,
        argPrompt,
        labelExtract: labelExtractRaw,
        ...ui,
      });
    }
  }
  return out;
}

function parseTagArray<T extends string>(
  raw: unknown,
  tag: string,
  field: "affects" | "requires",
  valid: ReadonlySet<T>,
  errs: Errors,
): readonly T[] | undefined | "invalid" {
  if (raw === undefined) return undefined;
  if (!Array.isArray(raw)) {
    errs.add(`${tag}.${field} must be an array of strings`);
    return "invalid";
  }
  const out: T[] = [];
  let bad = false;
  for (const v of raw) {
    if (typeof v !== "string") {
      errs.add(`${tag}.${field} entries must be strings`);
      bad = true;
      continue;
    }
    if (!valid.has(v as T)) {
      const allowed = [...valid].join(", ");
      errs.add(`${tag}.${field}: unknown tag "${v}" (allowed: ${allowed})`);
      bad = true;
      continue;
    }
    out.push(v as T);
  }
  if (bad) return "invalid";
  // Dedupe so `["git", "git"]` doesn't fan out to two invalidations
  // (or two precondition checks). Order is preserved.
  return [...new Set(out)];
}

function parseAffects(
  raw: unknown,
  tag: string,
  errs: Errors,
): readonly EffectTag[] | undefined | "invalid" {
  return parseTagArray(raw, tag, "affects", VALID_EFFECT_TAGS, errs);
}

function parseRequires(
  raw: unknown,
  tag: string,
  errs: Errors,
): readonly RequireTag[] | undefined | "invalid" {
  return parseTagArray(raw, tag, "requires", VALID_REQUIRE_TAGS, errs);
}

function load(): { cfg: Config; path: string } {
  const { path, present } = configPath();
  const errs = new Errors();
  const userRaw = loadRaw(path, present, errs);
  const repository = repositoryConfigPath();
  let raw = userRaw;
  let sourcePath = path;
  if (repository) {
    const repositoryRaw = loadRaw(repository, existsSync(repository), errs);
    raw = mergeConfig(userRaw, repositoryRaw);
    sourcePath = repository;
    process.env[REPOSITORY_CONFIG_ENV] = repository;
  }
  const cfg = build(raw, errs);
  // `[paths]` naturally lives in a repository `.wt.toml`; a bare `wt`
  // outside any repo then fails with "paths.main_clone is required" and
  // no clue where the field was expected. Name both candidate homes.
  const hints: string[] = [];
  if (!repository && errs.has("paths.")) {
    hints.push(
      `no .wt.toml was found from ${process.cwd()} upward — [paths] can live in a ` +
        `repository .wt.toml (run wt inside that repo) or in ${path} as the fallback ` +
        `used everywhere else`,
    );
  }
  errs.flush(sourcePath, hints);
  return { cfg, path: sourcePath };
}

const loaded = load();

export const config: Config = Object.freeze(loaded.cfg) as Config;

/**
 * Assert SST is configured and return its config. Call from code paths
 * that only make sense with `[deploy.sst]` set (the `wt stages` command,
 * `core/sst.ts` helpers). Throws a user-readable error if not.
 */
export function requireSst(): SstConfig {
  if (!config.sst) {
    throw new Error("[deploy.sst] is not configured in config.toml");
  }
  return config.sst;
}
