import { describe, expect, test } from "bun:test";
import { mkdtempSync, readFileSync, rmSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { Effect } from "effect";

import {
  detectBaseBranch,
  initializeRepository,
  renderInitConfig,
  run,
} from "./init.ts";

describe("detectBaseBranch", () => {
  test("prefers origin's declared default branch", () => {
    const git = (_cwd: string, args: readonly string[]) =>
      args.includes("refs/remotes/origin/HEAD") ? "origin/staging" : "main";
    expect(detectBaseBranch(git, "/repo")).toBe("staging");
  });

  test("prefers a conventional local main head over a feature checkout", () => {
    const git = (_cwd: string, args: readonly string[]) => {
      const last = args.at(-1);
      if (last === "refs/heads/main") return "sha";
      if (last === "HEAD") return "feature";
      return null;
    };
    expect(detectBaseBranch(git, "/repo")).toBe("main");
  });
});

test("renderInitConfig isolates cache and tmux by path-derived id", () => {
  expect(renderInitConfig({
    repoRoot: "/Users/alex/dev/cz/cozee-dev",
    baseBranch: "staging",
    repoId: "dev-cz-cozee-dev",
    home: "/Users/alex",
  })).toBe(`# Generated by \`wt init\`.
[paths]
main_clone = "~/dev/cz/cozee-dev"
worktree_root = "~/dev/cz/cozee-dev-worktrees"
cache_db = "~/.cache/wt/dev-cz-cozee-dev/cache.sqlite"

[tmux]
socket = "wt-dev-cz-cozee-dev"

[branch]
base = "staging"
`);
});

describe("initializeRepository", () => {
  test("finds the Git root from a nested directory and writes once", () => {
    const writes: Array<[string, string]> = [];
    const git = (_cwd: string, args: readonly string[]) => {
      if (args.at(-1) === "--show-toplevel") return "/Users/alex/dev/project";
      if (args.includes("refs/remotes/origin/HEAD")) return "origin/main";
      return null;
    };
    const result = initializeRepository("/Users/alex/dev/project/src", {
      home: "/Users/alex",
      git,
      exists: () => false,
      write: (path, content) => writes.push([path, content]),
    });
    expect(result).toMatchObject({
      ok: true,
      configPath: "/Users/alex/dev/project/.wt.toml",
      repoId: "dev-project",
    });
    expect(writes).toHaveLength(1);
  });

  test("refuses to overwrite an existing repository config", () => {
    const result = initializeRepository("/repo", {
      home: "/home/me",
      git: (_cwd, args) => args.at(-1) === "--show-toplevel" ? "/repo" : null,
      exists: () => true,
      write: () => { throw new Error("must not write"); },
    });
    expect(result).toEqual({ ok: false, message: "/repo/.wt.toml already exists" });
  });
});

describe("init --primary", () => {
  for (const primary of ["claude", "codex", "opencode"]) {
    test(`writes ${primary} with the flag before or after the directory`, async () => {
      for (const flagFirst of [false, true]) {
        const directory = mkdtempSync(join(tmpdir(), "wt-init-primary-"));
        try {
          expect(Bun.spawnSync(["git", "init", "-b", "main", directory]).exitCode).toBe(0);
          const args = flagFirst
            ? ["--primary", primary, directory]
            : [directory, "--primary", primary];
          expect(await Effect.runPromise(run(args))).toBe(0);
          const content = readFileSync(join(directory, ".wt.toml"), "utf8");
          expect(Bun.TOML.parse(content)).toMatchObject({ harness: { primary } });
        } finally {
          rmSync(directory, { recursive: true, force: true });
        }
      }
    });
  }

  test("rejects invalid or missing primary before creating a config", async () => {
    const directory = mkdtempSync(join(tmpdir(), "wt-init-invalid-"));
    try {
      for (const args of [[directory, "--primary", "other"], [directory, "--primary"]]) {
        expect(await Effect.runPromise(run(args))).toBe(2);
        expect(existsSync(join(directory, ".wt.toml"))).toBe(false);
      }
    } finally {
      rmSync(directory, { recursive: true, force: true });
    }
  });
});
