import { describe, expect, test } from "bun:test";

import {
  detectBaseBranch,
  initializeRepository,
  renderInitConfig,
} from "./init.ts";

describe("detectBaseBranch", () => {
  test("prefers origin's declared default branch", () => {
    const git = (_cwd: string, args: readonly string[]) =>
      args.includes("refs/remotes/origin/HEAD") ? "origin/staging" : "main";
    expect(detectBaseBranch(git, "/repo")).toBe("staging");
  });

  test("prefers a conventional local main head over a feature checkout", () => {
    const git = (_cwd: string, args: readonly string[]) => {
      const last = args.at(-1);
      if (last === "refs/heads/main") return "sha";
      if (last === "HEAD") return "feature";
      return null;
    };
    expect(detectBaseBranch(git, "/repo")).toBe("main");
  });
});

test("renderInitConfig isolates cache and tmux by path-derived id", () => {
  expect(renderInitConfig({
    repoRoot: "/Users/alex/dev/cz/cozee-dev",
    baseBranch: "staging",
    repoId: "dev-cz-cozee-dev",
    home: "/Users/alex",
  })).toBe(`# Generated by \`wt init\`.
[paths]
main_clone = "~/dev/cz/cozee-dev"
worktree_root = "~/dev/cz/cozee-dev-worktrees"
cache_db = "~/.cache/wt/dev-cz-cozee-dev/cache.sqlite"

[tmux]
socket = "wt-dev-cz-cozee-dev"

[branch]
base = "staging"
`);
});

describe("initializeRepository", () => {
  test("finds the Git root from a nested directory and writes once", () => {
    const writes: Array<[string, string]> = [];
    const git = (_cwd: string, args: readonly string[]) => {
      if (args.at(-1) === "--show-toplevel") return "/Users/alex/dev/project";
      if (args.includes("refs/remotes/origin/HEAD")) return "origin/main";
      return null;
    };
    const result = initializeRepository("/Users/alex/dev/project/src", {
      home: "/Users/alex",
      git,
      exists: () => false,
      write: (path, content) => writes.push([path, content]),
    });
    expect(result).toMatchObject({
      ok: true,
      configPath: "/Users/alex/dev/project/.wt.toml",
      repoId: "dev-project",
    });
    expect(writes).toHaveLength(1);
  });

  test("refuses to overwrite an existing repository config", () => {
    const result = initializeRepository("/repo", {
      home: "/home/me",
      git: (_cwd, args) => args.at(-1) === "--show-toplevel" ? "/repo" : null,
      exists: () => true,
      write: () => { throw new Error("must not write"); },
    });
    expect(result).toEqual({ ok: false, message: "/repo/.wt.toml already exists" });
  });
});
