import { existsSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import {
  basename,
  dirname,
  isAbsolute,
  join,
  relative,
  resolve,
} from "node:path";

import { repositoryNamespace } from "../../core/config-layer.ts";
import { hasHelpFlag } from "../args.ts";
import { Data, Effect } from "effect";

export class InitCommandError extends Data.TaggedError("InitCommandError")<{
  cause: unknown;
}> {}

const USAGE = `usage: wt init [directory]

Create a repository-local .wt.toml. The directory may be anywhere inside
the repository and defaults to the current directory. Detects the Git root
and trunk branch, creates a sibling <repo>-worktrees root, and assigns an
isolated cache namespace and tmux socket derived from the repository path.

Refuses to overwrite an existing .wt.toml.`;

type GitRunner = (cwd: string, args: readonly string[]) => string | null;

export type InitResult =
  | { ok: true; configPath: string; repoId: string; content: string }
  | { ok: false; message: string };

function runGit(cwd: string, args: readonly string[]): string | null {
  const result = Bun.spawnSync(["git", "-C", cwd, ...args], {
    stdout: "pipe",
    stderr: "pipe",
  });
  if (result.exitCode !== 0) return null;
  const value = result.stdout.toString().trim();
  return value === "" ? null : value;
}

/** Prefer the remote's declared default, then conventional local heads. */
export function detectBaseBranch(git: GitRunner, repoRoot: string): string {
  const remoteHead = git(repoRoot, [
    "symbolic-ref",
    "--quiet",
    "--short",
    "refs/remotes/origin/HEAD",
  ]);
  if (
    remoteHead?.startsWith("origin/") &&
    remoteHead.length > "origin/".length
  ) {
    return remoteHead.slice("origin/".length);
  }
  for (const candidate of ["main", "master"]) {
    if (git(repoRoot, ["rev-parse", "--verify", `refs/heads/${candidate}`])) {
      return candidate;
    }
  }
  return (
    git(repoRoot, ["symbolic-ref", "--quiet", "--short", "HEAD"]) ?? "main"
  );
}

function displayPath(path: string, home: string): string {
  const fromHome = relative(home, path);
  if (fromHome === "") return "~";
  if (!fromHome.startsWith("..") && !isAbsolute(fromHome))
    return `~/${fromHome}`;
  return path;
}

function tomlString(value: string): string {
  return JSON.stringify(value);
}

export function renderInitConfig(input: {
  repoRoot: string;
  baseBranch: string;
  repoId: string;
  home?: string;
}): string {
  const home = resolve(input.home ?? homedir());
  const root = resolve(input.repoRoot);
  const worktreeRoot = join(dirname(root), `${basename(root)}-worktrees`);
  const cacheDb = join(home, ".cache", "wt", input.repoId, "cache.sqlite");
  return `# Generated by \`wt init\`.
[paths]
main_clone = ${tomlString(displayPath(root, home))}
worktree_root = ${tomlString(displayPath(worktreeRoot, home))}
cache_db = ${tomlString(displayPath(cacheDb, home))}

[tmux]
socket = ${tomlString(`wt-${input.repoId}`)}

[branch]
base = ${tomlString(input.baseBranch)}
`;
}

export function initializeRepository(
  directory: string,
  deps: {
    home?: string;
    git?: GitRunner;
    exists?: (path: string) => boolean;
    write?: (path: string, content: string) => void;
  } = {},
): InitResult {
  const target = resolve(directory);
  const git = deps.git ?? runGit;
  const repoRoot = git(target, ["rev-parse", "--show-toplevel"]);
  if (!repoRoot) {
    return { ok: false, message: `${target} is not inside a Git repository` };
  }
  const configPath = join(resolve(repoRoot), ".wt.toml");
  const exists = deps.exists ?? existsSync;
  if (exists(configPath)) {
    return { ok: false, message: `${configPath} already exists` };
  }
  const repoId = repositoryNamespace(configPath, deps.home ?? homedir());
  const content = renderInitConfig({
    repoRoot,
    baseBranch: detectBaseBranch(git, repoRoot),
    repoId,
    home: deps.home,
  });
  const write =
    deps.write ?? ((path, text) => writeFileSync(path, text, { flag: "wx" }));
  try {
    write(configPath, content);
  } catch (err) {
    return {
      ok: false,
      message: `could not create ${configPath}: ${err instanceof Error ? err.message : String(err)}`,
    };
  }
  return { ok: true, configPath, repoId, content };
}

export function run(argv: string[]): Effect.Effect<number, InitCommandError> {
  return Effect.gen(function* () {
    if (hasHelpFlag(argv)) {
      console.log(USAGE);
      return 0;
    }
    const unknown = argv.find((arg) => arg.startsWith("-") && arg !== "-");
    if (unknown) {
      console.error(`unknown flag: ${unknown}\n\n${USAGE}`);
      return 2;
    }
    if (argv.length > 1) {
      console.error(`expected at most one directory\n\n${USAGE}`);
      return 2;
    }
    const result = yield* Effect.try({
      try: () => initializeRepository(argv[0] ?? process.cwd()),
      catch: (cause) => new InitCommandError({ cause }),
    });
    if (!result.ok) {
      console.error(result.message);
      return 1;
    }
    console.log(`created ${result.configPath}`);
    console.log(`namespace ${result.repoId}`);
    return 0;
  });
}
